### ISSUE TITLE
this arguments in constructor inappropriately placed before super() call

### ISSUE THREAD

**Issue by rmehlinger** [decaffeinate/decaffeinate#1100]
In CoffeeScript, it is possible to write a constructor whose arguments are immediately assigned as fields when called:

```
class Foo
  constructor: -> console.log 'hello'
class Bar extends Foo
  constructor: (@a, @b) ->
    console.log @a, @b
```

This is of course shorthand for the following:
```
class Bar extends Foo
  constructor: (a, b) ->
    @a = a
    @b = b
    console.log @a, @b
```

Unfortunately, when running decaffeinate on such a class, we receive the warning that we are referencing `this` before calling `super`. It seems like this is a pretty clear special case that could be handled by calling super before assigning the arguments to their corresponding properties.

**Comment by alangpierce** [comment]
Hey @rmehlinger, thanks for the thoughts, and I've been thinking about ways to make this case better. Unfortunately, I think putting the assignments after super can lead to bugs.

(Technically, in your case, the error is that you have a subclass constructor that never calls super. That's allowed in CoffeeScript and simply skips the super constructor, but it's not allowed in JavaScript classes. But sounds like you meant to have a `super` call in the constructor.)

Here's a case where I think your suggestion would introduce a bug:

```coffee
class A
  constructor: ->
    console.log @a

class B extends A
  constructor: (@a) ->
    super

new B(7)
```

That prints 7 when run through CoffeeScript. If you convert it to this:

```js
class A {
  constructor() {
    console.log(this.a);
  }
}

class B extends A {
  constructor(a) {
    super(...arguments);
    this.a = a;
  }
}

new B(7);
```

Then it will print "undefined". Unfortunately, this case comes up a number of times in my codebase at work, since in Backbone it's reasonably common to have superclass constructors that assume that particular fields are set. The result is callbacks that aren't properly bound and other really subtle issues.

This is a fundamental limitation of JavaScript classes compared with CoffeeScript classes; in CoffeeScript, you have your `this` from the start of the constructor and are free to make modifications to it before calling `super`. In JavaScript classes, the `super` call provides your with your `this`, so you have no way to make changes ahead of time.

As mentioned in the error message, you can convert the code anyway using `--allow-invalid-constructors` or `--enable-babel-constructor-workaround`.

I can think of two solutions here:
* Set `--enable-babel-constructor-workaround` by default (which adds a 7-line snippet to the top of the constructor to trick babel and typescript into allowing `this` before `super`). That's how I was able to get tests passing in my codebase at work and in the open-source projects in the README. It's ugly, but seems to work fine, and realistically it's very common for people to use babel or typescript. And it gives people time to rework their code after conversion to JavaScript rather than it blocking decaffeinate. I've been thinking of changing the default behavior to this, with a warning, but let me know if you have thoughts about that.
* Add an option to move `super` before the first usage of `this`. Like you mentioned, this is often correct, especially for simple cases like field assignments and method bindings that aren't accessed by the super constructor. I'm generally a bit hesitant to add options that could lead to subtle bugs, but it seems reasonable as long as people carefully test the code after decaffeinate.

Let me know if you have any thoughts on those.

**Comment by alangpierce** [comment]
In #1121, I changed it so the Babel workaround is enabled by default and it shows a warning. It's still a little hacky, but I think it's as good as decaffeinate can do.

[Here's what it looks like now](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=class%20Foo%0A%20%20constructor%3A%20-%3E%20console.log%20'hello'%0Aclass%20Bar%20extends%20Foo%0A%20%20constructor%3A%20(%40a%2C%20%40b)%20-%3E%0A%20%20%20%20console.log%20%40a%2C%20%40b)
