### ISSUE TITLE
Template literals appends a backwards slash to every line

### ISSUE THREAD

**Issue by madskonradsen** [decaffeinate/decaffeinate#1104]
Perhaps this is actually a non-issue, but nevertheless it doesn't look pretty :)

decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
a = """
      d
      """
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=MainStage&code=a%20%3D%20%22%22%22%0A%20%20%20%20%20%20d%0A%20%20%20%20%20%20%22%22%22)
I get this error:
I get this output:

```js
a = `\
d\
`;
```

Here's what I expect it to be instead:

```js
a = `
d
`;
```

**Comment by alangpierce** [comment]
Hey @madskonradsen . This is actually intentional, but happy to hear suggestions on how to improve it. Your suggested output is actually incorrect because the expected behavior is for it to just be the string `"d"` with no newline characters, but your output gives `"\nd\n"` since JS multiline strings include their newline characters. The escaped newlines are there so that the source code looks as close to the original source code as possible while still having the correct result. The general strategy that decaffeinate uses to handle multiline strings is to *escape* newline characters that need to be removed from the string rather than just removing them like the CoffeeScript compiler does.

As a more illustrative example, this CoffeeScript code:

```coffee
x = """
  abcde
  fghij
  klmno
  pqrst
  uvwxy
"""

y = "
  abcde
  fghij
  klmno
  pqrst
  uvwxy
"
```

Becomes this in the CoffeeScript compiler:

```js
var x, y;

x = "abcde\nfghij\nklmno\npqrst\nuvwxy";

y = "abcde fghij klmno pqrst uvwxy";
```

And decaffeinate produces this:

```js
let x = `\
abcde
fghij
klmno
pqrst
uvwxy\
`;

let y = `\
abcde \
fghij \
klmno \
pqrst \
uvwxy\
`;
```

**Comment by madskonradsen** [comment]
Oh, that makes perfect sense now. Never thought of the escaping as I just thought that it was an artifact. I can't come up with a better solution at the moment but will re-open if I happen to come up with something :) Btw. I'm extremely impressed by how the project has turned out over the past year! :) Remember to relax once in a while :D
