### ISSUE TITLE
question

### ISSUE THREAD

**Issue by publicocean0** [decaffeinate/decaffeinate#1168]
i d like call your tool programmatically. 

How can i convert a coffe script in js (synchronous way) programmatically?

**Comment by alangpierce** [comment]
Hi! It's not very common to call decaffeinate programmatically from JS, so it's not very well-tested, but it should just work. If you install decaffeinate as a library, you can use the `convert` function on the decaffeinate module to synchronously convert code.

Quick example in the node repl:
```
$ node
> const decaffeinate = require('decaffeinate');
undefined
> decaffeinate.convert('a b').code;
'a(b);'
```

You can read the convert function in the code to see what options it supports (which are pretty much analogous to the command line options):
https://github.com/decaffeinate/decaffeinate/blob/master/src/index.ts#L43
https://github.com/decaffeinate/decaffeinate/blob/master/src/options.ts

(Closing since this is answered, but happy to answer any follow-up questions.)

**Comment by publicocean0** [comment]
thanks i m working on it 
but i have last problem . Usually in the converter there is a option for passing the current directory used for import /include instruction. 

I saw the options:
export type Options = {
  filename?: string,
  runToStage?: string | null,
  literate?: boolean,
  disableSuggestionComment?: boolean,
  useOptionalChaining?: boolean,
  noArrayIncludes?: boolean,
  useJSModules?: boolean,
  looseJSModules?: boolean,
  safeImportFunctionIdentifiers?: Array<string>,
  preferLet?: boolean,
  looseDefaultParams?: boolean,
  looseForExpressions?: boolean,
  looseForOf?: boolean,
  looseIncludes?: boolean,
  looseComparisonNegation?: boolean,
  disableBabelConstructorWorkaround?: boolean,
  disallowInvalidConstructors?: boolean,
};
but i dont see how to tell the the parser the current folder.

**Comment by alangpierce** [comment]
Sorry, I'm not familiar with bindep, so I don't understand the context or use case very well.

decaffeinate doesn't need to know the current folder because it doesn't resolve imports/includes, it just converts to JavaScript code that has the same `require` call.

It sounds like you're maybe trying to use decaffeinate as part of a build system? If that's the case, you should just use the CoffeeScript compiler ( https://github.com/jashkenas/coffeescript ) instead. decaffeinate is a tool that people usually run on individual files to help speed up the process of manually rewriting CoffeeScript code into modern, clean JavaScript.

**Comment by publicocean0** [comment]
Yes bindep  extends the bower definition for building system ,permitting automatic    source injections directly in the pages (writing just the component to use), handling complex project using many modules  ( loaded based on your selection), to use preprocessor, to add resources . it permits also to convert automatically sources from a format to the final format: in this context sometime happens to find a bower project using coffee or typescript so i m trying to add a converter from coffee to javascript. You anwer is sufficient. If coffee script dont permits imports  ... it is sufficient  so :) Thanks for your kind support
