### ISSUE TITLE
clarification about generated bound methods

### ISSUE THREAD

**Issue by nebulousdog** [decaffeinate/decaffeinate#1169]
I'm sorry this doesnt fit the contribution guidelines, this is just a question I couldn't find in the docs.

What is the criteria for `decaffeinate` making bound methods?

I've decaffeinated a few viewmodels and some have all methods bound, such as `this.myMethod = this.myMethod.bind(this)` where `myMethod` was originally written like `myMethod: (param) => { /* do something */ }` and is now `myMethod(param) { /* do something */ }` and I can remove the bind lines to no effect.

thanks in advance! this tool is incredibly helpful.

**Comment by alangpierce** [comment]
Hey @nebulousdog, you're certainly welcome to file issues to ask questions, and I'll update the issue template to mention that.

If you have a specific example you want explained, you could link to a [repl](http://decaffeinate-project.org/repl/) code sample. But generally, `=>` on methods is a CoffeeScript feature that doesn't exist in JavaScript, and the equivalent in JavaScript is to explicitly bind the method in the constructor.

It's needed when you access the method without calling it and then call it later, like in this example:

```coffee
class A
  constructor: (@x) ->
  f: => @x
  
a = new A(5)
f = a.f
console.log(f())
```

[Repl link](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=class%20A%0A%20%20constructor%3A%20(%40x)%20-%3E%0A%20%20f%3A%20%3D%3E%20%40x%0A%20%20%0Aa%20%3D%20new%20A(5)%0Af%20%3D%20a.f%0Aconsole.log(f()))

This prints "5". If you use `->` instead of `=>`, the code crashes in strict mode and prints undefined outside of strict mode, since the `this` isn't properly sent to the method call. So if you ever use a method in that way, you need to keep the `this.myMethod = this.myMethod.bind(this)` line in the resulting JS for your code to be correct. This is particularly common for things like event listeners.

In terms of converting idiomatic CoffeeScript to idiomatic JavaScript, I think it's more common in JavaScript to only bind methods in the constructor when necessary, and leave the other methods unbound. Alternatively, rather than sending `this.myMethod` as a callback, you could send `() => this.myMethod()`, which keeps the proper `this`, or you could use `this.myMethod.bind(this)` when using it as a callback.

**Comment by nebulousdog** [comment]
Thanks for the thorough explanation! you answered my question.
