### ISSUE TITLE
Embedded js comments failure

### ISSUE THREAD

**Issue by martinkadlec0** [decaffeinate/decaffeinate#1176]
Hi, our application is full of inline embedded js comments. Unfortunately, decaffeinate is crashing on this CoffeeScript input:

```coffee
a = (`/** comment */`) b
```
[(repl)](http://decaffeinate-project.org/repl/#?evaluate=false&stage=full&code=a%20%3D%20(%60%2F**%20comment%20*%2F%60)%20b%0A)

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (1:19)
> 1 | a = (/** comment */)(b);
```

It seems decaffeinate unlike coffeescript isn't removing the parentheses.

**Comment by alangpierce** [comment]
Thanks for reporting! I'm a bit surprised that this works, to be honest. It looks to me like CoffeeScript is parsing it as a function call, which is why both decaffeinate and CoffeeScript put parens around the `b`. It happens to work because the resulting JS views the parens as normal parens around `b` that don't do anything.

It looks to me like it's correct to remove parens around any embedded JS, so hopefully the fix should be relatively easy.

**Comment by martinkadlec0** [comment]
Unfortunately, it doesn't work without the parens. If you remove them you get "NormalizeStage failed to parse: unexpected identifier" error in both decaffeinate and coffeescript.

**Comment by martinkadlec0** [comment]
Thank you!
