### ISSUE TITLE
Generate source map

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#119]
This will help with error messages referencing lines that don't exist, as in #115.

**Comment by eventualbuddha** [comment]
This is not as easy as it should be because combining source maps is a pain. I attempted to use https://github.com/Rich-Harris/sorcery to do it, but I believe magic-string was generating bad source maps or sorcery wasn't handling them properly.

**Comment by alangpierce** [comment]
@eventualbuddha I think the "run to stage" repl option and error message improvements have been a pretty good solution for showing errors at intermediate stages. And that problem is also less of an issue now that crashes are much more rare. Do you know of any other use case for source maps? It would certainly be awesome to have `git blame` somehow use source maps, but I think it's probably unlikely that git would ever support that.

I think it may make sense to close this issue and remove the existing source map code, unless you know of any other case where they would be useful.
