### ISSUE TITLE
Monorepo?

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#1218]
I think with the advent of Yarn Workspaces that it might make sense to turn decaffeinate and its related packages into a monorepo. What do you think, @alangpierce?

**Comment by alangpierce** [comment]
No strong objections, although decaffeinate is pretty much done, so I don't know if tech debt cleanup is so important. 😄I haven't ever set up a monorepo, so certainly seems reasonable for educational reasons, similar to moving to TypeScript.

Some possible concerns and things to think about:
* Yarn Workspaces supposedly are just a building block, and I think it's best to still use Lerna, e.g. for publishing, but use their flag that enables the use of Yarn Workspaces. ( https://yarnpkg.com/lang/en/docs/workspaces/#toc-how-does-it-compare-to-lerna )
* It's unclear if we'd still be able to use semantic-release.
* I rely on "git blame" quite a bit (to remember weird edge cases from a long time ago), and would want to make sure we preserve history. I think that should be possible, but it's some additional effort.
* Do you know how CI would work? Would we just run CI for all projects on every change, or is it reasonable to do something smarter based on what changed?
* I've had trouble in WebStorm when working with the Babel repo. I think Lerna ends up setting up circular symlinks, which confuses Webstorm and causes it to index forever in an infinite loop. It's possible that yarn workspaces doesn't run into that and/or that it only comes up if your packages have circular dependencies of some sort, but something to watch out for.
* We'd have to think about how versioning will work. Lerna's default behavior is to release all packages with the same version, Babel-style, but it has a mode that lets you pick independent versions. I guess I'd be fine either way, but possibly it would be an awkward transition given that decaffeinate-parser is on major version 19.
* It's unclear which packages should actually go there. The full list of projects that I can think of: decaffeinate, decaffeinate-parser, coffee-lex, decaffeinate-traverse (although maybe we should get rid of that one), decaffeinate-coffeescript, bulk-decaffeinate, add-variable-declarations, lines-and-columns, automatic-semicolon-insertion, esnext, decaffeinate-examples, decaffeinate-project.org. (decaffeinate-example-builder needs to be its own GitHub project due to Travis limitations.) Thoughts on which ones makes sense?
* I was thinking that we'd maybe want to support CoffeeScript 2 (which has some breaking changes in the parser) by publishing a decaffeinate-coffeescript2 package and depending on both from decaffeinate-parser, with an option controlling which one is used. My thought was that we could just have two branches in the coffeescript fork repo that publish under different package names, but that wouldn't really work if it was in the monorepo.

**Comment by eventualbuddha** [comment]
Sorry, left this fallow for a while. I think you covered all the things to consider quite well! I think it's probably best to leave it as-is unless you want to take it on. This would serve as a good todo list in such a case 😄
