### ISSUE TITLE
Paramter defaults for passed-in null values are different in coffeescript and es6 

### ISSUE THREAD

**Issue by jcalfee** [decaffeinate/decaffeinate#125]
Null passed in coffee-script resolves as to the parameter's default value but resolves as `null` in es6.  Only `undefined` in es6 will capture a default value.

``` coffeescript
    Aes.decrypt_with_checksum = (private_key, public_key, nonce = "", message) ->
```

should convert to

``` js
Aes.decrypt_with_checksum = function(private_key, public_key, nonce, message) {
  if (nonce == null) {
    nonce = "";
  }
}
```

This will not work:

``` js
    Aes.decrypt_with_checksum = function(private_key, public_key, nonce = "", message) {
    };

```

**Comment by eventualbuddha** [comment]
Ugh, that's sad. Probably best to make this an option.

**Comment by an-sh** [comment]
Sorry for the duplicate. The best option for me: for any code by
default it should produce semantically 100% equivalent or fail with an
error otherwise. So the first is rewriting the coffee (for missing in
es6 itself or this convertor features), then compilation will give
100% identical functionally. Better missing some constructs support,
that an incorrect output. In this work-flow model no debugging of es5
output is required.

For this case, probably it will be good to have some flag (default
disabled) that will enable es6 default params usage.

**Comment by alangpierce** [comment]
For a first pass, I'll just implement the conditional assignment code without leaving in the default or adding the comment. Those can be added later if we think they're useful.
