### ISSUE TITLE
Babel / TS constructor hack gets optimized away using UglifyJS

### ISSUE THREAD

**Issue by hilts-vaughan** [decaffeinate/decaffeinate#1303]
Hi all!

If you put a random Coffeescript class through Decaf with Babel constructor hacks enabled, then run it through, say, here: https://skalman.github.io/UglifyJS-online/ with the constructor class. Say, with the following input:

```
class ConstructorHackDemo extends Backbone.Model {
  constructor(...args) {
    {
      // Hack: trick Babel/TypeScript into allowing this before super.
      if (false) { super(); }
      let thisFn = new Function('this');
      let thisName = thisFn.slice(thisFn.indexOf('{') + 1, thisFn.indexOf(';')).trim();
      eval(`${thisName} = this;`);
    }
    super(...args);
  }
}
```

... UglifyJS will then optimize part of the line away to read, say:

```
            let thisFn = (() => {}).toString(), thisName = thisFn.slice(thisFn.indexOf("{") + 1, thisFn.indexOf(";")).trim();
```

I think this is to be expected with stock settings. It persists even if you decide to to toggle `dead_code` or  `unused` I'll play around with it.

It seems to play better if you force it to think it's used, i.e:

```
let thisFn = (() => { return this; }).toString();
```

... and updating the below lines. Is this known? Not strictly an issue with decaf and I'm working around it right now but I noticed one of your goals was a "great out of the box experience" for many projects. :)

Or some other variant such as `new Function`

Great project 👍

**Comment by hilts-vaughan** [comment]
... or switching to say, "new Function("this")" would fix this.. optimizer seems to leave it alone.

**Comment by alangpierce** [comment]
Hi @hilts-vaughan, thanks for the report and the thoughts. For reference, here's the full constructor hack code snippet:
```
    {
      // Hack: trick Babel/TypeScript into allowing this before super.
      if (false) { super(); }
      let thisFn = (() => { this; }).toString();
      let thisName = thisFn.slice(thisFn.indexOf('{') + 1, thisFn.indexOf(';')).trim();
      eval(`${thisName} = this;`);
    }
```
There are two pieces here:
* Babel and TypeScript do static analysis checks to make sure that `super` at least has a chance of being called before the first use of `this`, so `if (false) { super(); }` tricks them into allowing it.
* Both Babel and TypeScript create a variable called `_this` that acts as the "real this" for the function, and all usages of `this` become `_this` in the compiled code. For Babel (but not TypeScript), it isn't initialized until the real `super` call below, but we can initialize it earlier it by executing the code `_this = this;`. Unfortunately, it's not *always* called `_this`; occasionally it's `_this2` or similar, so we need to do other hacks to find the name of the compiled `_this`: we make a function containing `this` and parse the compiled body.

Sounds like the issue is that `() => { this; }` is becoming `() => {}`, so the code trying to parse the `this` name isn't working? Unfortunately, `new Function("this")` wouldn't work either, since we need Babel to rewrite `this` into `_this` or `_this2` or whatever it decides.

Your `() => { return this; }` suggestion seems like it would work and seems safe, but note that the parsing would need to change. I'd be happy to accept a PR to change it to that.

A few other thoughts:
* The hack is on by default in decaffeinate because in at least some configurations it works, and because it's probably easier to fix up the hacky code than for it to block decaffeinate. Unfortunately, it still is far from ideal, and it doesn't surprise me that it would break with Uglify. This is the one case in decaffeinate where there really isn't a good solution, but at least the hack works sometimes.
* When I was running decaffeinate, I tried shipping code with the constructor hack and it failed in the build system due to istanbul modifying the function body. I think generally any code modification tools are likely to break it. I ended up just fixing every constructor rather than trying to use the hack in production.
* You probably should be running uglify after babel, right? So really, uglify will run on the compiled code, whatever that happens to be. But I think your suggested fix should still work.
* Alternatively, if you're using TypeScript, we maybe could have an option that only does the `if (false) { super(); }`, since that's much less error-prone and only that one is needed in TypeScript.

**Comment by hilts-vaughan** [comment]
I've also filed a bug with UglifyJS since it seems like they are technically modifying behaviour, which against their goals: https://github.com/mishoo/UglifyJS2/issues/3075

**Comment by alangpierce** [comment]
@hilts-vaughan Cool, sounds good. FWIW you should be able to see how much works by just disabling uglify; while I was working on decaffeinate, I was able to use the constructor hack to run all unit tests and try everything out in development; it was just the CI tests and the production build that wouldn't work.

For the PR, I think the main interesting part is writing a test (which I think doesn't exist yet). You could add a test at the bottom of `class_test.ts` that uses the `validate` function to make sure the runtime behavior is the same as CoffeeScript, particularly the function parsing code. You should pass `skipNodeCheck: true` since we don't expect the constructor hack to work when run without babel. CS2 doesn't allow `this` before `super`, so you should just do `validateCS1` I think.

**Comment by hilts-vaughan** [comment]
Yep, without Uglify everything works fine. But for a real test, of course, I want to make sure Uglify has not broken anything that this produces. (Which of course, it did.) I assume that without the constructor hack, everything should be good. :)
