### ISSUE TITLE
Remove Babel/TypeScript constructor workaround doesn't work

### ISSUE THREAD

**Issue by artem-barmin** [decaffeinate/decaffeinate#1324]
It seems like "Remove Babel/TypeScript constructor workaround" solution doesn't work.
I have a code:
````javascript
constructor(_gui, container) {
        {
          // Hack: trick Babel/TypeScript into allowing this before super.
          if (false) { super(); }
          let thisFn = (() => { return this; }).toString();
          let thisName = thisFn.slice(thisFn.indexOf('return') + 6 + 1, thisFn.indexOf(';')).trim();
          eval(`${thisName} = this;`);
        }
        this.createElement('div');
    }
````
The script has error in eval(`${thisName} = this;`) - "Invalid left-hand side in assignment"

**Comment by alangpierce** [comment]
@artem-barmin I just tested it and it does work, but to be clear, it's only meant to work in certain configurations. You need to use either Babel or TypeScript, and it must be configured to compile classes to ES5. In my testing just now, it looks like Babel 7 (still in beta) doesn't work anymore because it became more defensive, but Babel 6 works and latest TypeScript still work.

In all other configurations, I'm not aware of anything decaffeinate can do automatically to avoid crashing or introducing subtle bugs. In your case, it looks like you're never calling `super` from a subclass constructor, which works in CoffeeScript but will crash in JavaScript. If it's a mistake to leave out `super`, then you might be able to just add it to your CoffeeScript (which might change your program's behavior) to fix the problem.

In general, the constructor workaround does work in many common configurations, but even in those configurations, it's fragile. I would recommend removing those code snippets and fixing the surrounding code right after running decaffeinate, or you can change your CoffeeScript code ahead of time to follow the JavaScript rules (`super` must be called exactly once, and must be called before all `this` usages) before running decaffeinate.

In case you haven't seen it, there are more docs here:
https://github.com/decaffeinate/decaffeinate/blob/master/docs/suggestions.md#ds001-remove-babeltypescript-constructor-workaround

Closing for now, but feel free to reopen if you think there's still something to be addressed.
