### ISSUE TITLE
Multiline import w/o commas

### ISSUE THREAD

**Issue by a-x-** [decaffeinate/decaffeinate#1365]
decaffeinate is crashing on my CoffeeScript input:

```coffee
import {
  a
  b
} from 'boo'
```

[repl](https://decaffeinate-project.org/repl/#?useCS2=true&useJSModules=true&loose=true&evaluate=true&stage=full&code=import%20%7B%0A%20%20a%0A%20%20b%0A%7D%20from%20'boo'%0A)

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token, expected ","
```

**Comment by eventualbuddha** [comment]
This is happening because decaffeinate assumes it doesn't need to rewrite import statements:

https://github.com/decaffeinate/decaffeinate/blob/82e78df0d872b8392154fdb5d2e4a22af6a0696a/src/stages/main/index.ts#L377-L383

This would be a fairly easy thing to fix since it's almost exactly the same as the comma insertion code for function calls:

https://github.com/decaffeinate/decaffeinate/blob/82e78df0d872b8392154fdb5d2e4a22af6a0696a/src/stages/main/patchers/FunctionApplicationPatcher.ts#L36-L54

**Comment by a-x-** [comment]
What coffeescript repl you use?
it's must have for me

**Comment by eventualbuddha** [comment]
I typically just use the one at https://decaffeinate-project.org/repl/ if I need to examine something. What are you trying to do with the repl?
