### ISSUE TITLE
Convert to latest JS

### ISSUE THREAD

**Issue by aleksandrlat** [decaffeinate/decaffeinate#1382]
I have a feature request.

For now `decaffeinate` outputs not recent JS code. Please help to output JS code with all recent features supported by babel. I see `decaffeinate-parser` which looks cool. 
I think I just need to update `nodes.coffee`?

**Comment by eventualbuddha** [comment]
Can you provide an example?

**Comment by aleksandrlat** [comment]
Sure. For example my class was converted to something like
```
class AllObjectsForm extends BaseComponent {
    static initClass() {
        // PROPERTIES TO OVERWRITE
        this.prototype.displayName = 'AllObjectsForm';
    }

    getAll() {
        return [];
    }

    constructor(props) {
         super(props);
         this.getAll = this.getAll.bind(this);
    }
}
AllObjectsForm.initClass();
```

But I want it to be like this:
```
class AllObjectsForm extends BaseComponent {
    displayName = 'AllObjectsForm'

    getAll = () => {
         return [];
    }
}
```

**Comment by eventualbuddha** [comment]
I see. So you had something like this:

```coffee
class AllObjectsForm extends BaseComponent
  displayName: 'AllObjectsForm'
  
  getAll: =>
    []
```

And you want decaffeinate to assume that it's okay to use class properties. This is kind of tricky to get right, since the behavior is actually different. In CoffeeScript you're just assigning an object to the prototype, which is why decaffeinate does the `initClass` thing to do exactly that. In JavaScript that class property assignment happens each time the object is constructed, so you end up with something like this (desugared):

```js
class AllObjectsForm extends BaseComponent {
  constructor(...args) {
    super(...args);
    this.displayName = 'AllObjectsForm';
    this.getAll = () => {
      return [];
    };
  }
}
```

This is almost exactly the same, but this version has a subtle difference: `new AllObjectsForm().getAll !== new AllObjectsForm().getAll`. This could lead to subtle bugs in your code base if anything was assuming that `getAll` would be identical across instances. It's not hard to come up with examples where the difference matters a lot:

```coffee
class A
  list: []
```

In this, `A.prototype.list` is actually the same array object in every instance. This is probably a bug, but one that your code may rely on. Changing it to this "equivalent" will change behavior:

```js
class A {
  list = [];
}
```

In this version, every instance of `A` gets its own list. This is probably what you want, but doesn't match the original behavior.

That said, this could be done safely for anything that is known to be immutable, i.e. string and number literals. If you're interested in submitting a PR for that, add another comment saying so and I'll point out where you need to look. You shouldn't have to touch decaffeinate-parser.

**Comment by aleksandrlat** [comment]
Thank you @eventualbuddha very much for such detailed explanation!

I didn't know that properties are not instance properties. This was not obvious. I'm relatively new in coffeescript.

And I don't understand about `new AllObjectsForm().getAll !== new AllObjectsForm().getAll`
Because with 
```
constructor(props) {
    super(props);
    this.getAll = this.getAll.bind(this);
}
```
`new AllObjectsForm().getAll !== new AllObjectsForm().getAll` too. Because `bind` creates new function.

Yes please let me know I want to fix it at least for literals. It can be beneficial for community and for me. I learn it and I can fork to modify for our needs after.

**Comment by eventualbuddha** [comment]
You'll likely need to edit [`ClassPatcher#needsInitClass`](https://github.com/decaffeinate/decaffeinate/blob/4da99ddc0f3c30f724e1db747fedc5c0f8a702af/src/stages/normalize/patchers/ClassPatcher.ts#L140-L154) and the methods it calls, notably [this line](https://github.com/decaffeinate/decaffeinate/blob/4da99ddc0f3c30f724e1db747fedc5c0f8a702af/src/stages/normalize/patchers/ClassPatcher.ts#L221).
