### ISSUE TITLE
Add support for `for` loops used as expressions

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#156]
Including implicit returns, e.g.

```coffee
a(b for b in c)
->
  for a in b
    a
```

**Comment by d4rky-pl** [comment]
Is there any workaround?

**Comment by kazazor** [comment]
Hi @eventualbuddha - I can see that you've already developed this issue, but I still getting this error when trying to use it:
```'for' loops used as expressions are not yet supported (https://github.com/decaffeinate/decaffeinate/issues/156)```

It is truly on master and being used by this [repl](http://decaffeinate.github.io/decaffeinate/repl/)?

**Comment by sethcall** [comment]
I was also going to ask, say I have something like this:
```
Junk = {
  c: () ->
    d

  d: () ->

    for a in b
      @c()

}
```

What do I do to re-write it such that I can workaround this decaffeinate limitation?  It's not clear to me that there is a way out on this. Thanks for any help.

**Comment by eventualbuddha** [comment]
The easiest way to work around it is just to add a `return` after the loop at the end of the function.

**Comment by sethcall** [comment]
That works!

**Comment by alangpierce** [comment]
Hey @eventualbuddha, I'm thinking of tackling this one pretty soon (or at least part of it). I wonder if you have thoughts on any challenges or edge cases. I saw that the normalize step gets rid of the post-for form, so that should make things simpler.

My current thought is to rewrite `for...in` like this:
`for a in b then c` -> `b.map(a => c)`

And when there's a filter, something like this:
`for a in b when c then d` -> `b.filter(a => c).map(a => d)`

For `for...of` I was thinking of doing a similar thing using `Object.keys` and `Object.entries`, but I guess that only goes over own properties and not properties in the prototype chain. Maybe we could emit a helper that generates the right properties and just filter/map on that? (It looks like `for...in` is much more common in the codebase I'm porting, though, so I may just focus on that.)

I guess another concern is that if the body has a `break`, `continue`, or `return`, then it wouldn't work inside the lambda. That seems kind of rare, though (especially for expression for loops), so maybe as a first pass I could just fail for that case.

Does that seem reasonable? I saw in some of the test cases in `for_test.js` that you have expected code using an IIFE with a regular for loop, so I wonder if there's more that I haven't thought of. I guess technically `map` wouldn't work if the target is an array-like object that exposes `length` and indexing at int indices, but doesn't have a `map` method. Do you think that's a case we care about?

**Comment by alangpierce** [comment]
Ok, I'm trying to close out the remaining cases for this one, hopefully I'll be able to get a working PR. It looks like the while loop patcher already has code to patch a loop as an IIFE, so I'm going to try to extend that to work on all types of loops. This doesn't necessarily result in the best code (e.g. `for own` expressions would sometimes be better written as `Object.keys(...).map(...)` or `Object.entries(...).map(...)`), but it should make it so decaffeinate generates correct code for all loop expressions.
