### ISSUE TITLE
no patcher available for node type: SoakedFunctionApplication

### ISSUE THREAD

**Issue by niieani** [decaffeinate/decaffeinate#176]
I've tried decaffeinating this file: https://github.com/rethinkdb/rethinkdb/blob/next/drivers/javascript/cursor.coffee

But I'm getting the error:

```
cursor.coffee: no patcher available for node type: SoakedFunctionApplication (props: function, arguments)
  223 |             if err?
  224 |                 if err.message is 'No more rows in the cursor.'
> 225 |                     onFinished?()
      |                     ^^^^^^^^^^^^^
  226 |                 else
  227 |                     cb(err)
```

**Comment by flying-sheep** [comment]
also: soaked member access:

```coffeescript
a?.b or c
```

**Comment by andrewaustin** [comment]
Simple repro case: 

http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=false&code=a%20%3D%20(callback)%20-%3E%0A%20%20callback%3F()%0A%20%20

**Comment by eventualbuddha** [comment]
I've updated the error messages to point to this issue. Unfortunately the fix is not straightforward for the general case, but some simple cases might be handled specially.

**Comment by niieani** [comment]
Since there's no equivalent of soakes in ES6, why not simply use the CoffeeScript compiler for those parts? I don't see any other solution anyway, unless you'd want to introduce helper methods to increase readability.

**Comment by madskonradsen** [comment]
I see that the simple `obj.property?` gets handled in a nice way and converted to `obj.property != null`. What about using simple `&&` for handling the other cases? Like converting `obj.property?.anotherProperty` into `obj.property && obj.property.anotherProperty` ?

**Comment by niieani** [comment]
`&&` is not exactly the same as `!== undefined`; plus what you get is a boolean not the value of the second invocation -- but I know what you meant by that.
The thing is some code might depend on strict checking (e.g. an empty string could be a value) and that would generate bugs. I agree that in 99% cases that won't be the case, but it still shouldn't be the default behavior - perhaps if this is opt in? Using `!= null` for every case will be very verbose, but correct; `&&` would be the 'loose' equivalent (similarly to how babel has `-loose` versions of some of the transformations).

An alternative is to emit a helper method like `exists(thing)` and then desugar coffeescript like so:
```js
function exists(value) {
  return value != null;
}

// from
obj.property?.anotherProperty

// to
if (exists(obj.property)) obj.property.anotherProperty
```

Or even cooler, with a `maybe(thing)`:

```js
function maybe(value) {
  return value != null ? value : {};
}

// from
obj.property?.anotherProperty

// to
maybe(obj.property).anotherProperty
```

**Comment by niieani** [comment]
Good discussion on ways of dealing with this and caveats of using `&&`:
- https://github.com/Microsoft/TypeScript/issues/16
- https://esdiscuss.org/topic/existential-operator-null-propagation-operator
- https://phabricator.babeljs.io/T855

**Comment by sethyates** [comment]
:+1: We use this along with the application I raised in #216 all over the place, so this is a blocker for us using this to convert any code.

**Comment by madskonradsen** [comment]
I agree with you @niieani ! As you mention, a loose-option(for also using `&&` on member access) for that type might be a great start. Also, for the last 1% of the cases that doesn't work, it should be caught by peoples unit tests ;) I just tried to kickstart the discussion at esdiscuss, but it doesn't look like they care, and even if they did, it would take years before it got implemented. 
Also, i just noticed that the SoakedFunctionApplication works a bit different as it gets compiled into:
`if (typeof myFunction === "function") {
    myFunction();
}`
sigh

**Comment by sethcall** [comment]
👍  We use this a ton. If it can be supported, it's great for us too.

**Comment by nordfjord** [comment]
This is a blocker for me as well. Soaks are for me one of the greatest features of coffeescript and I'm sad there isn't an equivalent operator in es2015 :/

99.99999% of my cases they could be replaced with `&&` guarding

**Comment by niieani** [comment]
Yeah, I think in the end we should do `&&` by default as it's the right thing in 99.9% cases and emit a warning that it's not strict, with an option for emitting the stricter, default CoffeeScript output for the soaks.

**Comment by alangpierce** [comment]
My big worry about `&&` is when dealing with non-repeatable expressions (ones where it's unsafe to write it twice), especially deeply-nested ones. Here's an example that doesn't map nicely to `&&`:

```
showAAs: -> @visibilityOption.getSetting('show-orf-amino-acids')?.get('value') == 'checked'
```

Technically there is the `makeRepeatable` approach (described in the [Contribution Guide](https://github.com/decaffeinate/decaffeinate/blob/master/docs/contribution-guide.md)) that sticks an assignment into the middle of the expression, but that seems really ugly to me, especially for something that's going to come up a lot.

My impression is that the right approach is to have a safe "baseline" implementation, maybe using a helper method, and then add special cases for when there's a nicer thing we can do or for when we're willing to sacrifice 100% correctness for conciseness (maybe as an option).

I really like the `maybe` solution suggested by @niieani, but I think it only works for `a?.b` and `a?[b]`, not `a?.b(c)` or `a?(b)`. One challenge with making a helper for soaked function calls is that the arguments shouldn't be evaluated unless the check passes. Here's one approach that I think would work:

```
function guard(value, f) {
  if (value != null) {
    return f(value);
  }
}
```

You could then use it like this:

```
guard(this.visibilityOption.getSetting('show-orf-amino-acids'), x => x.get('value')) == 'checked'
```

Certainly not as pretty as `?.`, but it's nice in that the left-hand-side only appears once and I think the transform would be fairly easy to implement (although there may be nuances with the use of lambdas that I'm overlooking). Of course, that wouldn't preclude `&&` or similar for simpler cases.

**Comment by niieani** [comment]
@alangpierce good point. However it's impossible to tell (for the compiler) which are the simpler cases, after all, any expression could involve side-effects. Perhaps emitting `&&` with a TODO comment for manual checking would make most sense? 
Would you have a real-life example where soaks are used on function where there are side-effects that might cause the function to evaluate differently the second time?

**Comment by alangpierce** [comment]
> any expression could involve side-effects

No, there are some expressions that definitely can't, like if the expression is just a variable. Decaffeinate already has an `isRepeatable` method on patchers that determines if it's safe to repeat the code. Individual variables, expressions like `a.b`, and expressions like `a[b]` are all considered repeatable (even though technically property accesses could invoke getters with side-effects, but according to [a comment](https://github.com/decaffeinate/decaffeinate/blob/master/src/stages/main/patchers/MemberAccessOpPatcher.js#L98), this behavior is in-line with CoffeeScript).

I did a random sample of uses of `?.` in my codebase, and 6 out of 10 were repeatable, so they could be turned into `&&` without a lot of headache. But there are still plenty of cases where the left side is a function call.


> Would you have a real-life example where soaks are used on function where there are side-effects that might cause the function to evaluate differently the second time?

I tried looking in my code, and the closest thing I could find in real-world code is a `currentUser()?.referral` expression, where `currentUser` does a lot of work, but from my reading it never does any log statements or network I/O or anything. Still, it's wasteful to call it twice.

But here's a made-up example that I think is realistic:
`workQueue.pop()?.process()`

It gets and removes the next item of work, if there is any, and processes it. If we repeated the left side, it would skip every alternate item.

And in general, I think that for any explicit function calls in the code, it's important to preserve the number of times they're called and the order in which they're called. That also means that it's risky to extract a function call into a variable at the top of the function, since the function would be called earlier than before.

**Comment by niieani** [comment]
Very good examples. 👍  Thanks.

**Comment by alangpierce** [comment]
I'm taking a closer look at this and it turns out it's a lot harder than I thought. `?.` isn't just a binary operator that can be transformed in isolation, it changes the behavior of the whole chain of operations that it's a part of.

For example, this line only invokes the `c` function if `a` isn't null or undefined:
```coffee
a?.b = c()
```

and this example does the smart thing of doing two null checks and only proceeding forward when the null check passes:
```coffee
a.b.c?.d.e.f?.g.h
```

and these two lines behave differently:
```coffee
a?.b.c
```
```coffee
(a?.b).c
```

That last example is particularly tricky because (from what I can tell) decaffeinate-parser parses them into the same AST. The regular CoffeeScript parser treats them differently, so it should be possible to modify decaffeinate-parser to produce an AST with enough information to distinguish them.

As far as the actual patching goes, the `maybe` function above kind of falls apart in a lot of these cases, but I think my `guard` function still works. Here's what the above cases would end up as:

```js
guard(a, x => x.b = c())
guard(a.b.c, x => guard(x.d.e.f, y => y.g.h))  // or maybe guard(guard(a.b.c, x => x.d.e.f), y => y.g.h)
guard(a, x => x.b.c)
guard(a, x => x.b).c
```

So hopefully it's just a matter of identifying each "soak range", putting "guard(" at the front, ", x => x" in the middle, and ")" at the end. (Of course, in simpler cases we can still do simpler things like `&&`.)

For the decaffeinate-parser changes, it looks like the CoffeeScript parser generates a "Parens" node to distinguish these cases, which decaffeinate-parser ignores. So I think a good first step is to keep Parens nodes in the AST produced by decaffeinate-parser. Their only purpose, at least for now, will be to act as some sort of boundary when searching for soak operations and defining soak ranges.

@eventualbuddha or anyone else, happy to hear thoughts or advice if you have more info on this stuff. I'll also probably dig into the CoffeeScript source code at some point to get a better understanding of how all this works.

**Comment by alangpierce** [comment]
Ok, I just put up a PR with the strategy I mentioned: #324. I ended up just using the `isSurroundedByParentheses` function instead of modifying decaffeinate-parser to include that information.

**Comment by alangpierce** [comment]
Ok, PR is merged and released, so soak operations work now using a `__guard__` helper. I just filed #336 to generate nicer-looking code in the most common cases.
