### ISSUE TITLE
How to go about soaking?

### ISSUE THREAD

**Issue by flying-sheep** [decaffeinate/decaffeinate#185]
Hi, I have no deep understanding on how decaffeinate works.

am i right that basically every node type that can be handled will be *replaced* by a “<NodeType>Patcher” in the AST, and then those patchers will be run in some order, finally creating a patched AST?

If so, which order? from innermost to outer? outer to inner?

if i want to use `insert` and `overwrite`, when does the transition to JS happen? can i do e.g.

```js
const expr = this.node.expression;
expr.patch();

this.insert(this.outerStart, `if (${expr.raw} != null) { `);
this.insert(this.outerEnd, ' }');
this.overwrite(expr.outerEnd, this.InnerEnd, `.{this.node.memberName}`)
```

when exactly comes `patchAsStatement` into play?

---

Now about the specifics of soaks:

Basically they need to be handled on the statement level:

2. when appearing in an argument position, it needs to compile to a trinary: `a(b?.c)` ⇒ `a(b != null ? b.c : undefined)`.

so basically:

* we use a conditional (`if thing != null`)

	1. if the LHS of an assignment statement contains a soaked member access (`a?.b = c`)
	2. we have a function call *statement* with a soak to the left or a soaked function call *statement* (`a?.b()` or `a?()`)

* we use a trinary

	1. if anything with a soak appears as function call argument or the RHS of an assignment (`a(b?.c)`, `a = b?.c`, `a(b = c?.d)`)

* we use an extracted temporary variable if a (soaked or unsoaked) function call is to the *left* of a soak (so we don’t re-call the function when reusing the part to the left of the soak)

---

all of this means we can’t just have `SoakedMemberAccessOpPatcher` and friends, but need to conditionally dispatch on function call statements, assignment statements function argument expressions.

what’s the best architecture for this? dispatch inside of the big switch statement?

```js
case 'AssignOp':
  return containsSoakedMemberAccess(node.assignee)
    ? SoakedAssignOpPatcher
    : AssignOpPatcher;
```

or do we extend e.g. `FunctionApplicationPatcher::patchAsStatement`? (if that even works)

**Comment by eventualbuddha** [comment]
Hey @flying-sheep! Thanks for looking into contributing. Have you seen [the contributing guide](https://github.com/decaffeinate/decaffeinate/blob/master/docs/contribution-guide.md)? That answers some of your questions. I'll put a few inline here:

> am i right that basically every node type that can be handled will be replaced by a “Patcher” in the AST, and then those patchers will be run in some order, finally creating a patched AST?

Essentially, yes. Really what's happening is that a parallel tree is of patchers is created, and those patchers don't patch the AST but the original source string.

> If so, which order? from innermost to outer? outer to inner?

The patchers determine the order within themselves, but it's close to a depth-first traversal that ends up patching the source string from left to right. For example, transforming `a b: c` would patch starting at the root and end up patching the string from left to right, i.e.

```
$ echo 'a b: c' | env 'DEBUG:*=1' ./bin/decaffeinate 
…
FunctionApplicationPatcher OVERWRITE [1, 2) " " → "("
ObjectInitialiserPatcher INSERT 2 "{" BEFORE "b: c\n"
ObjectInitialiserPatcher INSERT 6 "}" BEFORE "\n"
FunctionApplicationPatcher INSERT 6 ")" BEFORE "\n"
BlockPatcher INSERT 6 ";" BEFORE "\n"
…
a({b: c});
```

> when exactly comes `patchAsStatement` into play?

Hopefully this is answered in the guide I linked to, but `patchAsStatement` is used when the node being patched is in a statement position, i.e. its value is not being used.

As for your question about how to handle soaks…

> what’s the best architecture for this?

That's still up in the air. I think your understanding of it is pretty much right. Keep in mind that soaks have weird non-local effects, such as:

```coffee
a?.b?.c = d
```

becoming

```js
if (a != null) { if (a.b != null) { a.b.c = d } }
```

I had a branch where I partially implemented this, but haven't revisited in a while. I'll dig it up and push it so you can take a look. Soaked function applications are easier, and I actually almost have that working. I'll create a PR and cc you on it.

I'm closing this since there's not really anything this is tracking, but feel free to continue posting replies here.

**Comment by flying-sheep** [comment]
> Have you seen the contributing guide?

no, turns out i’m stupid :laughing:

thanks for the answers!

the only thing i still don’t get is what happens if you rewrite children. will the children’s patchers still run or does this invalidate and recreate the child tree?

> Keep in mind that soaks have weird non-local effects, such as: `a?.b?.c = d`

yes, sadly this is exactly the opposite order than the nesting of the AST nodes.

so basically we’ll have to deep dive into every statement/expression that might contain soaks, i.e. most of them, and wrap them into a conditional/trinary if so.

> ```js
> a?.b?.c = d
> ```
> 
> becoming
> 
> ```js
> if (a != null) { if (a.b != null) { a.b.c = d } }
> ```

or this if we feel like making this complex:

> if (a != null && a.b != null) { a.b.c = d }

**Comment by flying-sheep** [comment]
oh, one question: what’s `no-const-except-at-top` supposed to do?

i consider it to be an antipattern to *not* use `const` wherever possible

**Comment by eventualbuddha** [comment]
I was in the same boat re: `let` vs `const`, but changed my mind after reading this: https://madhatted.com/2016/1/25/let-it-be

**Comment by flying-sheep** [comment]
nah, i don’t buy it.

> aggressive use of const devalues the operator

`const` + `ALLCAPS` = only at top level, module level consts

`const` + `snake_case` = only in functions, bindings that don’t change

> The suggestion is that now, when adding a re-assignment, the developer should go back and change the message declaration to let. What was the value of making it a constant then?

because back then, a reader knew it wouldn’t be changed during program execution. now it will be changed during program execution as the program flow changed. it’s adapting guarantees to new truths.

i think the author didn’t think that through. will conform to your code style in PRs though

**Comment by flying-sheep** [comment]
OK, back to topic. a remaining question:

> the only thing i still don’t get is what happens if you rewrite children. will the children’s patchers still run or does this invalidate and recreate the child tree?

and the main problem IMHO:

> so basically we’ll have to deep dive into every statement/expression that might contain soaks, i.e. most of them, and wrap them into a conditional/trinary if so.

i.e. we must create and use `containsSoaks` on e.g. `assignee` in `AssignOpPatcher` and friends or inside of the big switch statement. am i right?
