### ISSUE TITLE
global object defaults to undefined, not global

### ISSUE THREAD

**Issue by graingert** [decaffeinate/decaffeinate#202]
this accessors like @Foo when defined in the global scope become:

``` js
(functon() {
   this.Foo;
}).call(this);
```

in Coffeescript

and 

``` js
this.Foo;
```

in decaffeinate.

which gets babel'd to:

``` babel
undefined.Foo;
```

in decaffeinate.

**Comment by eventualbuddha** [comment]
I'm not really sure what decaffeinate can do about this. I could add a warning, I suppose.

**Comment by graingert** [comment]
You could replace with (typeof x! == undefined  ? x : undefined)

**Comment by eventualbuddha** [comment]
But `x` is always `this`, right? Oh, I see, change `@Foo` to attempt to resolve as a global instead. Hmm, maybe…

**Comment by graingert** [comment]
x isn't this it's a property of this. I think it would be great as it's the
intention behind top level @ vars

**Comment by eventualbuddha** [comment]
Ironically, your proposed solution would conflict with the fix for #203. We can't change top-level `@Foo` to `(typeof Foo !== 'undefined' ? Foo : undefined)` everywhere. For example, `@Foo = 1` would create a syntax error since a ternary is not a valid assignee. Even if we tried to special-case it, it would have to remain an assignment to a member expression (i.e. `a.b = c`) since if we turned it into `Foo = 1` then it would implicitly become `var Foo = 1`.

**Comment by graingert** [comment]
In the script that I'm decaffeinating there's only one global assignment
but quite a lot of global accesses so I don't mind that other case.

To handle the assignment case, if global assignments are found, how about
we add:

let coffeeGlobal:

try {
  coffeeGlobal = Function('return this')() || (0, eval('this');
} catch(e) {
  coffeeGlobal = window;
}

Then use coffeeGlobal for top level @ assignments. (still use the undefined
ternary for access)

Using coffeeGlobal so that users know to fix it manually but at least it
works. (note in Europe 0.1% caffeine is still decaffeinated.)

**Comment by alangpierce** [comment]
This came up in the CoffeeScript compiler: it uses `@FILE_EXTENSIONS` and `@VERSION` in this file:
https://github.com/jashkenas/coffeescript/blob/master/src/coffee-script.coffee

In that case, since it's running in node, top-level `this` refers to `exports`. When using node and babel, `this` should probably be changed directly to `exports`, but without babel, `this ` can be left as-is.

Given the number of options here, I think it's probably best for decaffeinate to be unopinionated by default and just output `this`, and have options or follow-up transforms for specific cases. There's also #204, which makes sense; I think ideally decaffeinate would at least give a warning when it sees this and have documentation explaining the issue and the different possible solutions. For now, I'll close this issue in favor of #204, and I'll also try to get this working for the CoffeeScript repo using a custom jscodeshift transform in bulk-decaffeinate.
