### ISSUE TITLE
Error in template strings: cannot find first or last token in String node

### ISSUE THREAD

**Issue by madskonradsen** [decaffeinate/decaffeinate#227]
POC: http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=template%20%3D%20%22%22%22%0A%20%20%3Csomething%0A%20%20%20%20perperty-one%3D%22%23%7BsomeObj%7D%22%0A%20%20%20%20property-two%3D%22%23%7BsomeOtherObj%7D%22%0A%20%20%3E%3C%2Fsomething%3E%0A%22%22%22

The above example is valid coffeescript.

**Comment by mjleino** [comment]
I had the same issue. The quotes inside the block string is the problem. Notice how the code converts if you remove either the second (the one right after someObj) or third quote (the one just before someOtherObj) inside the block string.

**Comment by terite** [comment]
I ran into the same issue today

Fails:
```coffee
"""
foo="#{ foo }"
bar="#{ bar }"
"""
```

Workaround I'm using:
```
"""
foo="#{ foo }"
bar='#{ bar }'
"""
```

**Comment by alangpierce** [comment]
It this no longer crashes, probably due to https://github.com/decaffeinate/decaffeinate-parser/pull/71, but isn't properly putting newlines in the output string.

**Comment by alangpierce** [comment]
Some notes on this: it looks like the issue here is that the middle quasi starts and ends with a `"` character. When trying to reconstruct the string template information from the coffeescript parser output, the `quotesMatch` function in decaffeinate-parser checks if the raw code starts and ends with a `"`, and if so, assumes that it must be an interpolated expression rather than a quasi in the string, which ends up causing various problems later. The [decaffeinate-parser output](http://decaffeinate-project.org/repl/#?evaluate=true&stage=decaffeinate-parser&code=template%20%3D%20%22%22%22%0A%20%20%3Csomething%0A%20%20%20%20perperty-one%3D%22%23%7BsomeObj%7D%22%0A%20%20%20%20property-two%3D%22%23%7BsomeOtherObj%7D%22%0A%20%20%3E%3C%2Fsomething%3E%0A%22%22%22) shows that the quasis and expressions aren't what you'd expect them to be. I think the right fix is to use a smarter method to figure out what type of string it is, like cross-referencing with the coffee-lex tokens.
