### ISSUE TITLE
Interpolation in multi-line string leaves '#'

### ISSUE THREAD

**Issue by ryym** [decaffeinate/decaffeinate#252]
Hi, thanks for the great tool!
### Versions
- Node.js: 6.2.0
- decaffeinate: 2.13.1
### Problem

When I convert code like the following, string interpolation doesn't be converted correctly.

``` coffee
# coffee

value = 12

bad =
  """
  a
  #{value}
  """
```
#### Actual

``` javascript
// js

let value = 12;

let bad =
  `a
$#{value}`;
```
#### Expected

``` javascript
// js

let value = 12;

let bad =
  `a
${value}`;
```

But the folloing patterns are converted correctly.

``` coffee
# coffee

value = 12

ok1 = "a #{value}"

ok2 =
  """
  #{value}
  a
  """

# no indent
ok3 =
"""
a
#{value}
"""
```

``` javascript
// js

let value = 12;

let ok1 = `a ${value}`;

let ok2 =
  `${value}
a`;

// no indent
let ok3 =
`a
${value}`;
```

---

**EDIT:** Fixed sample code after @madskonradsen 's [comment](https://github.com/decaffeinate/decaffeinate/issues/252#issuecomment-226996725).

**Comment by madskonradsen** [comment]
Cannot reproduce anymore: [relp](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=true&code=value%20%3D%2012%0A%0Abad%20%3D%0A%22%22%22%0Aa%0A%23%7Bvalue%7D%0A%22%22%22)

**Comment by ryym** [comment]
@madskonradsen Sorry, my reproduction code is wrong. This occurs when the multi-line string is indented: [repl](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=true&code=value%20=%2012%0A%0Abad%20=%0A%20%20"""%0A%20%20a%0A%20%20#{value}%0A%20%20""")

**Comment by alangpierce** [comment]
It looks like the issue here is that decaffeinate uses the end of the quasi to determine where the `#` is, but in this case, decaffeinate-parser ends the first quasi at 6:1 when it should end at 6:3 (even though the actual contents of the quasi are removed due to leading indentation being removed). Here's the parser output: [repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=decaffeinate-parser&code=value%20%3D%2012%0A%0Abad%20%3D%0A%20%20%22%22%22%0A%20%20a%0A%20%20%23%7Bvalue%7D%0A%20%20%22%22%22).
