### ISSUE TITLE
Line breaks in a statement within parentheses fail with: "AddVariableDeclarationsStage failed to parse" error

### ISSUE THREAD

**Issue by niieani** [decaffeinate/decaffeinate#276]
Breaking example:
```coffee
(a) ->
  (a not in b.map(a, (e) -> 
    e)
  )
```

The same code without the newline after `(e) ->` works:
```coffee
(a) ->
  (a not in b.map(a, (e) -> e)
  )
```

**Comment by eventualbuddha** [comment]
([repl](http://decaffeinate-project.org/repl/#?evaluate=true&code=(a)%20-%3E%0A%20%20(a%20not%20in%20b.map(a%2C%20(e)%20-%3E%20%0A%20%20%20%20e)%0A%20%20)))

**Comment by iainb** [comment]
This is a regression, here is another example that has the same root cause/error.
```coffeescript
"""string
"""
```
With git bisect and the two examples I found that 0457cea650c02910a5f47bf5683f8036e85169c9 introduced the regression.

Most likely the change in isMultiline() within the NodePatcher.

```diff
diff --git a/src/patchers/NodePatcher.js b/src/patchers/NodePatcher.js
index e089aea..f3136c5 100644
--- a/src/patchers/NodePatcher.js
+++ b/src/patchers/NodePatcher.js
@@ -656,7 +656,7 @@ export default class NodePatcher {
    * Determines whether this patcher's node spanned multiple lines.
    */
   isMultiline(): boolean {
-    return /[\r\n]/.test(this.getOriginalSource());
+    return !this.node.virtual && /[\r\n]/.test(this.getOriginalSource());
   }
 
   /**
```

**Comment by alangpierce** [comment]
@iainb thanks for catching that! Interestingly, it works when the file does not have a trailing newline ([repl](http://decaffeinate-project.org/repl/#?evaluate=true&code=%22%22%22string%0A%22%22%22)) but fails when the file does have a trailing newline ([repl](http://decaffeinate-project.org/repl/#?evaluate=true&code=%22%22%22string%0A%22%22%22%0A)).

When you say that it has the same root cause/error, do you just mean that they both have the "AddVariableDeclarationsStage failed to parse" error? Unfortunately, that's a pretty generic error meaning that the initial JavaScript created by decaffeinate had a syntax error in it. It looks to me like the original bug has an incorrectly-placed paren, whereas in your link, the `"""` never gets converted for some reason, so they seem to be different issues. Also, the original issue here was filed 13 days ago, and the commit you linked is from 5 days ago, so the original issue can't be a regression caused by that commit. Would you mind filing your issue as a separate bug?
