### ISSUE TITLE
Wrong super keyword compilation.

### ISSUE THREAD

**Issue by an-sh** [decaffeinate/decaffeinate#310]
decaffeinate version 2.17.1

```coffeescript
class C extends B
  constructor: (x) ->
    super

  fn: (x) ->
    super
```
```javascript
class C extends B {
  constructor(x) {
    super();
  }

  fn(x) {
    return super.fn();
  }
}
```
ES6 code should call super with `arguments` in this examples.

**Comment by eventualbuddha** [comment]
Yep, good catch. There's a wrinkle here that we need to look out for when implementing this. This works fine:

```coffee
functionWithRepeatableArguments: (a, b, c) ->
  super
```

```js
functionWithRepeatableArguments(a, b, c) {
  super.functionWithRepeatableArguments(a, b, c);
}
```

But what about this?

```coffee
functionWithDestructuringArguments: ([a], {b}) ->
  super
```

```
functionWithDestructuringArguments([a], { b }) {
  // ???
}
```

**Comment by alangpierce** [comment]
A related issue is that this crashes:
```coffee
class A
  b: ->
    c(super)
```
with the error "cannot edit index 28 because it is not editable (i.e. outside [22, 27))".

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&code=class%20A%0A%20%20b%3A%20-%3E%0A%20%20%20%20c(super))

Also, don't we basically need to use `arguments` (or maybe bind `...args`) here to be correct? For example, I think it's valid for a CoffeeScript method to declare no arguments at all, and an empty `super` call will still forward any arguments that were passed in. I don't have much experience with this, but I imagine it could be used for wrapper functions that don't care about what arguments they take, like this:
```coffee
class PrintingThingDoer extends ThingDoer
  doComplicatedThing: () ->
    console.log 'Doing thing'
    super
    console.log 'Done'
```

**Comment by rmacklin** [comment]
@eventualbuddha 
> But what about this?
> 
> ```coffee
> functionWithDestructuringArguments: ([a], {b}) ->
>   super
> ```
> ```js
> functionWithDestructuringArguments([a], {b}) {
>   // ???
> }
> ```

This:
```coffee
class Foo
  functionWithDestructuringArguments: ([a], {b}) ->
    super
```
[gets compiled to](http://coffeescript.org/#try:class%20Foo%0A%20%20functionWithDestructuringArguments%3A%20(%5Ba%5D%2C%20%7Bb%7D)%20-%3E%0A%20%20%20%20super):
```js

var Foo;

Foo = (function() {
  function Foo() {}

  Foo.prototype.functionWithDestructuringArguments = function(arg, arg1) {
    var a, b;
    a = arg[0];
    b = arg1.b;
    return Foo.__super__.functionWithDestructuringArguments.apply(this, arguments);
  };

  return Foo;

})();
```
so I think with or without destructuring, `super` needs to pass `arguments`, otherwise you risk producing ES6 code with breaking semantics.

**Comment by rmacklin** [comment]
[decaf](https://github.com/rainforestapp/decaf) produces (no repl link because it [seems to be down](https://github.com/rainforestapp/decaf/issues/162)):
```js
class Foo {
  functionWithDestructuringArguments(
    [a],
    {
      b
    }) {
    return super.functionWithDestructuringArguments(...arguments);
  }
}
```
(ugly formatting in the output but you can see it uses `arguments`)
