### ISSUE TITLE
False-positive "'for' loops used as expressions are not yet supported"-errormessage

### ISSUE THREAD

**Issue by madskonradsen** [decaffeinate/decaffeinate#320]
decaffeinate is crashing on my CoffeeScript input:

```coffee
 ->
  try
    something = ""
  catch err
    console.log err
  for file in files
    compilePath "hey"
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&code=%20-%3E%0A%20%20try%0A%20%20%20%20something%20%3D%20%22%22%0A%20%20catch%20err%0A%20%20%20%20console.log%20err%0A%20%20for%20file%20in%20files%0A%20%20%20%20compilePath%20%22hey%22)

I get this error:

```
'for' loops used as expressions are not yet supported (https://github.com/decaffeinate/decaffeinate/issues/156)
  4 |   catch err
  5 |     console.log(err)
> 6 |   for file in files
> 7 |     compilePath("hey")
```

When not wrapped in a function(->) it compiles just fine.

**Comment by alangpierce** [comment]
It's actually correct for it to be treating the for loop as an expression, since that's what CoffeeScript does. Since it's the last line of a function, CoffeeScript's behavior is to basically do `return for file in files...`, which ends up returning an array with the return value of each `compilePath` call. An easy fix is to put an empty return statement at the bottom, which decaffeinate handles fine ([repl](http://decaffeinate-project.org/repl/#?evaluate=true&code=%20-%3E%0A%20%20try%0A%20%20%20%20something%20%3D%20%22%22%0A%20%20catch%20err%0A%20%20%20%20console.log%20err%0A%20%20for%20file%20in%20files%0A%20%20%20%20compilePath%20%22hey%22%0A%20%20return)).

In the codebase I work on, we use the no-implicit-returns coffelint rule to avoid this kind of mistake:
https://www.npmjs.com/package/coffeelint-no-implicit-returns

**Comment by madskonradsen** [comment]
My bad... I was too quick on the draw! How could i forgot about implicit returns... *sigh*
