### ISSUE TITLE
`new` expressions with property access are converted incorrectly into call expressions

### ISSUE THREAD

**Issue by lennartjansson** [decaffeinate/decaffeinate#391]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
x = new A().B
```

[Here is a decaffeinate repl link](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=x%20%3D%20new%20A%28%29.B).

I get this output:

```js
let x = new A().B();
```

Here's what I expect it to be instead:

```js
let x = new A().B;
```

[Compare with what the `coffeescript` compiler produces:](http://coffeescript.org/#try:x%20%3D%20A%28%29.B)

```js
var x;

x = A().B;
```

**Comment by alangpierce** [comment]
Thanks for the report. Looks like CoffeeScript actually [produces this output](http://coffeescript.org/#try:x%20%3D%20new%20A().B):
```
var x;

x = new A().B;
```
(you forgot `new` when you entered it in your report)

Looks like this is a problem how `decaffeinate-parser` interprets the CoffeeScript AST. It's parsing it as `new (A().B)`, when it should be parsing it as `(new A()).B`.

As always, PRs are welcome :-) . Otherwise, I'll see if I can get to this when I get a chance (or maybe someone else will get to it).

**Comment by lennartjansson** [comment]
> Looks like CoffeeScript actually produces this output

Whoops, sorry, you're right!
