### ISSUE TITLE
Make using `const` when possible an option

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#408]
We should add a `--prefer-const` flag to the command line which translates to a `preferConst` option.

**Comment by GeoffreyBooth** [comment]
@eventualbuddha @alangpierce Forgive me for intruding on this issue, but we’ve been discussing `let` and `const` in the context of CoffeeScript 2 over in [this issue](https://github.com/coffeescript6/discuss/issues/35). I’m proposing a new operator `:=` that would basically be “block scope assign”—it would translate into `let`, or `const` if the compiler could detect that the variable wasn’t reassigned within the block. I’m unsure if we might also need a second operator, e.g. `:==`, to force `const`.

Anyway my question is, are there any cases where the CoffeeScript compiler might not be able to detect if it’s safe to declare/assign a variable with `const` instead of `let`? I know we can’t convert plain `=` into `const`, because `=` assumes `var` and function scope, whereas we need a way for people to specify that they want block scope, whether that means `let` or `const`; but I’m hoping that for `:=` at least, we can automatically use `const` whenever possible without people needing to tell the compiler explicitly.

**Comment by alangpierce** [comment]
Hey @GeoffreyBooth, no problem at all!

I think it's generally not hard to see if a `let` declaration can be `const`; you just need to follow the scoping rules and see if there are any assignments to the variable. I haven't done it myself, but @eventualbuddha implemented it in esnext a while back (which I just enabled in this commit):

https://github.com/esnext/esnext/blob/master/src/plugins/declarations.block-scope.js

and the [prefer-const](http://eslint.org/docs/rules/prefer-const) eslint rule can both detect and auto-fix cases where you should use `const`:

https://github.com/eslint/eslint/blob/master/lib/rules/prefer-const.js

One possibly weird case I've seen is code like this:

```coffee
[a, b] = c
a = d
```

Assuming you want to keep a single destructure declaration on the JS side, you'd need to use `let` even though `b` could by itself be declared const. This is the one case I know where eslint gives an error but also isn't willing to auto-fix the declaration.


IMO there isn't much value into automatically choosing `let` or `const` in generated JS code. I'd keep it simple and always output `let` for `:=`. At least from my experience, `const` is for programmer convenience; it makes it harder to make some types of mistakes, and it arguably makes code easier to read because it makes the intentions of variables more clear. I'm pretty sure babel won't even transpile your code if you try to assign to a `const` variable, so the runtime behavior never comes up in practice; it's all basically a compile-time check. (eslint also has a check for it, which I guess is useful for people who don't use babel.) If CS2 had `:==`, I would expect the compile step to fail if there's a reassignment, not just for `const` to appear in the JS code.

I haven't measured it, but I doubt `const` is any better in terms of performance. I've worked a little with JS engines, and I think it's relatively easy for a JS engine to look ahead and see if a `let` declaration is actually `const` in practice. I think modern JS implementations already do preprocessing and optimizations that are much more advanced than that.

FWIW, the decaffeinate projects all have a convention of using `let` rather than `const` everywhere (which is basically the "only `:=`" proposal), although in other code that I work on, I prefer `const` when possible. So my personal opinion is that either style is reasonable, and I certainly prefer `let` over `var`.

**Comment by GeoffreyBooth** [comment]
Wow, thanks for the detailed reply! Yes, you’re convincing me that automatic `const` is unnecessary; either we support it explicitly with its own operator, as a way for developers to add a check on their own work similar to static types, or we just leave it out entirely as redundant. I hope you don’t mind, I’m going to quote you in the other thread 😄

**Comment by alangpierce** [comment]
👍 glad my reply was helpful.
