### ISSUE TITLE
Failed to parse map returning a list of objects

### ISSUE THREAD

**Issue by andrewaustin** [decaffeinate/decaffeinate#411]
decaffeinate is crashing on my CoffeeScript input:

``` coffee
a = d.map (c) -> { "#{c.name}": true }
```

http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=a%20%3D%20d.map%20(c)%20-%3E%20%7B%20%22%23%7Bc.name%7D%22%3A%20true%20%7D%0A

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (1:33)
> 1 | a = d.map(function(c) { return { `${c.name}`: true }; });
    |                                  ^
  2 | 
```

**Comment by alangpierce** [comment]
Looks like the issue here is that CoffeeScript allows template strings as object keys, but JavaScript doesn't. Here's an example that's a little more reduced:
```coffee
{"#{a}": b}
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%7B%22%23%7Ba%7D%22%3A%20b%7D)

A simple general fix is to just add a special case where we put square brackets around the template string:

```js
{[`${a}`]: b}
```

But I guess in this case the intention is to use template strings as a way of doing computed keys in CoffeeScript, which doesn't support normal computed keys. So a better conversion in this case is:

```js
{[a]: b}
```

That's still correct because JavaScript computed properties convert their result to a string.

So probably the right fix is to have one special case for a template string key that is only a single expression, where it just gets rid of the template string altogether and leaves just the expression as the key (surrounded in square brackets), and a more general case for more complicated template strings as keys that puts square brackets around the converted template string.
