### ISSUE TITLE
Parsing error - method with condition

### ISSUE THREAD

**Issue by jj117** [decaffeinate/decaffeinate#419]
decaffeinate is crashing on my CoffeeScript input:

```coffee
@someMethod => 'returnValue' if condition
```

I get this error:

```
/usr/local/lib/node_modules/decaffeinate/dist/decaffeinate.js:10471
        throw err;
        ^

Error: unexpected string
  at ParseError.Error (native)
```

The following works as expected, however:

```coffee
@someMethod => ('returnValue' if condition)
```

**Comment by alangpierce** [comment]
Thanks for the report! Here's a [repl link](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%40someMethod%20%3D%3E%20'returnValue'%20if%20condition) for convenience.

By the way, the most recent version of decaffeinate (and thus the repl) reports errors a little better here.

The bug here is that the NormalizeStage changes `'returnValue' if condition` to `if condition then 'returnValue'`, and also puts parentheses around the `someMethod` function call, and the two transforms end up getting mixed up and the new close-paren gets put in the wrong place.

**Comment by jj117** [comment]
Ah, wasn't aware that error messages had been improved. Thanks!
