### ISSUE TITLE
Hang on embedded double quotes

### ISSUE THREAD

**Issue by stilist** [decaffeinate/decaffeinate#435]
decaffeinate is crashing on my CoffeeScript input:

```coffee
"#{"bar"}"
```

http://decaffeinate-project.org/repl/#?evaluate=false&code=%22%23%7B"bar"%7D%22

I get this error:

The parser pegs the CPU and hangs.

* * *

I encountered this issue while trying to convert a Backbone.js project. The actual code is

    "/air_quality?latitude=#{me.get "latitude"}&longitude=#{me.get "longitude"}"

but I was able to simplify it down to the snippet shown above.

Notes:

1. `"#{'bar'}"` works fine.
1. CoffeeScript (and the REPL on coffeescript.org) parse the double-quoted version fine.
1. I tried to have the REPL only run to the CoffeeScript lexer stage and it still locked up.
1. I tried some lightweight debugging with the web inspector by putting a breakpoint on `convert` and stepping through for a while. It *seems* like the issue is somewhere after the lexing, because the code generates a list of nodes and gets into `SourceTokenListIndex`, but I'm not familiar enough with the code to really know.

**Comment by alangpierce** [comment]
Thanks for the report! I imagine this is similar to or the same as https://github.com/decaffeinate/decaffeinate-parser/issues/14 (but still fine to leave this issue open). The decaffeinate-parser step needs to do some non-trivial work to reconstruct the AST for string interpolations, so this most likely is hitting an edge case in that.

The "run to stage" feature in the REPL always runs the first four steps, mostly because it makes the implementation a little simpler and usually doesn't matter, so that's why you were seeing a hang even with only the CS lexer specified.

**Comment by alangpierce** [comment]
Looks like this was actually a bug in coffee-lex (a decaffeinate-specific alternative lexer that is generally used instead of the official CoffeeScript lexer). I just submitted a fix: https://github.com/decaffeinate/coffee-lex/pull/51.

**Comment by stilist** [comment]
Great!
