### ISSUE TITLE
Multi line string fails with function call

### ISSUE THREAD

**Issue by vinnymac** [decaffeinate/decaffeinate#457]
decaffeinate is crashing on my CoffeeScript input:

``` coffee
String """
  Test Test Test
"""
```

[repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=String%20%22%22%22%0A%20%20Test%20Test%20Test%0A%22%22%22)

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token, expected , (1:9)
> 1 | String(""" Test Test Test """
    |          ^
  2 | );
```

Note, changing to the below syntax appears to work just fine:

``` coffee
"""
  Test Test Test
"""
```

[repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%22%22%22%0A%20%20Test%20Test%20Test%0A%22%22%22)

**Comment by alangpierce** [comment]
Thanks for reporting. I tracked this down and it turns out it's a bug in the CoffeeScript lexer/parser. The CoffeeScript lexer was giving the wrong location for the end of the string, so decaffeinate-parser thought the string included the implicitly-added close-paren,, so the string wasn't properly recognized as a triple-quoted string, so decaffeinate never ran the code to change triple-quoted strings to regular strings.

I submitted this fix, which should fix the issue: https://github.com/decaffeinate/coffeescript/pull/9

**Comment by vinnymac** [comment]
@alangpierce I find that very odd, since if I put the same problematic code into the [repl from coffeescript.org](http://coffeescript.org/#try:String%20%22%22%22%0A%20%20Test%20Test%20Test%0A%22%22%22) it appears to transpile just fine to ES5.

**Comment by alangpierce** [comment]
@vinnymac The bug only causes the *intermediate syntax tree representation* for CoffeeScript to be incorrect, not the compiled JS. It's supposed to provide the start and end position of every node, but it was giving wrong information in this case. The normal CoffeeScript compiler doesn't rely on that information (or at least, not as much), so it never caused any problems in the CoffeeScript output. But decaffeinate does an "in-place" transformation so that formatting is preserved as much as possible, so it relies heavily on the CoffeeScript parser providing correct location data.
