### ISSUE TITLE
yield problem 

### ISSUE THREAD

**Issue by Maxim-Chugaev** [decaffeinate/decaffeinate#516]
```javascript
models/Advertiser.coffee: AddVariableDeclarationsStage failed to parse: Unexpected token
return co(() => {
  advertiser=yield this.forge({id: id}).fetch({require: true});
             ^
```
original
```coffeescript
co =>
  advertiser = yield @forge(id: id).fetch require: true
```
whats wrong?

**Comment by alangpierce** [comment]
It looks like the issue here is that decaffeinate doesn't yet support `yield` within fat-arrow functions. For `->` functions, it converts it to `function*`, but there's no way to define a generator arrow function in JavaScript. I guess decaffeinate should use `function*` and add `.bind(this)` in this case.

In the meantime, you could manually change the code to use `->` and bind `this` before running it through decaffeinate.
