### ISSUE TITLE
NodeList is iterable, but does not have a `map` method

### ISSUE THREAD

**Issue by bengotow** [decaffeinate/decaffeinate#523]
Decaffeinate is producing the wrong JavaScript based on my CoffeeScript input.

When iterating over a NodeList with a for loop that has a single line loop body, Decaffeinate switches from a for loop to a `.map` call, which is not valid. NodeLists are iterable but do not have a map method.

One solution would be to use `Array.from(codeTags)` to cast it to an array, or not switch to using `map` at all.

```coffee
  onContentChanged: ({editor, mutations}) ->
    codeTags = editableNode.querySelectorAll('code.var.empty')
    for codeTag in codeTags
        codeTag.doSomething()
```
http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%20%20onContentChanged%3A%20(%7Beditor%2C%20mutations%7D)%20-%3E%0A%20%20%20%20codeTags%20%3D%20editableNode.querySelectorAll('code.var.empty')%0A%20%20%20%20for%20codeTag%20in%20codeTags%0A%20%20%20%20%20%20%20%20codeTag.doSomething()%0A

I get this output:

```js
  ({
    onContentChanged({editor, mutations}) {
      let codeTags = editableNode.querySelectorAll('code.var.empty');
      return codeTags.map((codeTag) =>
          codeTag.doSomething());
    }
  });
```

Here's what I expect it to be instead:

```js
  ({
    onContentChanged({editor, mutations}) {
      let codeTags = editableNode.querySelectorAll('code.var.empty');
      let output = [];
      for (let codeTag of codeTags) {
          output.push(codeTag.doSomething());
      }
      return output;
    }
  });
```

**Comment by alangpierce** [comment]
Thanks for the report. Yep, I've run into this type of thing as well, and it's a really tricky issue without an obvious solution, and I've been meaning to get feedback on it.

Two similar issues I've run into:
* In Safari, `FileList` is array-like but not iterable, so converting CS for-in to JS for-of causes a crash if the iteration is over a `FileList`.
* jQuery collections are now iterable (although they weren't in a previous version), but they have a `map` function that behaves differently from `Array.prototype.map` because it returns a jQuery collection. This is even worse because it doesn't crash but instead returns an incorrect result.

While the for loop building an array isn't so bad in your example, in general that wouldn't work because the loop is used as an expression and might be deep within some other expression where there's no clean place to declare variables or put a for loop. Currently the fallback for loop expressions is to wrap it in an IIFE. Not that your suggested transformation can't be done, but it would be a fairly complicated special case.

I've had a number ideas on how to approach this issue, none of which seem great:
* Make decaffeinate always produce code that matches CoffeeScript iteration semantics. [Here's a repl link](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%20%20onContentChanged%3A%20(%7Beditor%2C%20mutations%7D)%20-%3E%0A%20%20%20%20codeTags%20%3D%20editableNode.querySelectorAll('code.var.empty')%0A%20%20%20%20for%20codeTag%20in%20codeTags%20by%201%0A%20%20%20%20%20%20%20%20codeTag.doSomething()%0A) showing what it would look like in that case (I added `by 1` to the loop to trick decaffeinate into using fallback code). I worry that being overly safe here makes decaffeinate much less useful; it shouldn't just be the CoffeeScript compiler, it should try to produce nice code that you might have written yourself.
* Use `Array.from` on every loop and map call, even in the common case when it's already an array. This feels ugly to me, although maybe it wouldn't be so bad. Certainly nicer than an expanded loop within an IIFE.
* Make it a preference. This would be relatively easy (the `canPatchAsMapExpression` and `shouldPatchAsForOf` methods in [ForInPatcher](https://github.com/decaffeinate/decaffeinate/blob/master/src/stages/main/patchers/ForInPatcher.js#L81) already decide what strategy to use), but I'm not convinced that it's actually a matter of preference.
* Try doing something fancy to determine when we need to transform loops the safer way. For example, it's potentially possible to recognize that `codeTags` came from the result of `querySelectorAll`, so it's likely a `NodeList`. This certainly won't work in every case, but might help reduce the number of problems.
* Produce the ugly-but-correct code for all loops, but leave a comment suggesting that you clean up the code if possible.
* Produce the clean-but-sometimes-incorrect code for all loops, but leave a comment suggesting that you verify the code to make sure it doesn't hit this edge case.
* Document this edge case. This is a no-brainer, I just haven't gotten around to it yet.
* Add a polyfill for `NodeList`, `FileList`, and anything else that runs into this issue so that common array-like objects are also iterable and have `map`. To avoid keeping the polyfill around forever, you could log a warning in cases where the polyfill is needed and remove it when it's no longer used. I like this option, but it requires knowing ahead of time what needs to be polyfilled.

Happy to hear any feedback or other suggestions.

**Comment by alangpierce** [comment]
Another example: strings are array-like and iterable, but don't have `map`. Thinking about it more, I'm thinking it may be best to just always wrap the loop target in `Array.from`, at least for `map`, and probably for JS for-of loops as well. It's annoying because it means there will be a lot of unnecessary `Array.from` calls that should probably be removed manually later. But that's probably better than having subtle bugs pop up occasionally (in my codebase, there were two such bugs in about 4000 lines of code that I converted). Fortunately, `Array.from` is pretty concise compared with CoffeeScript's output.

Also, it may be possible to automate the process of detecting unnecessary `Array.from` by patching it to log a warning when the argument was just an array, then running the test suite or trying to exercise all code paths some other way.
