### ISSUE TITLE
decaffeinate crashes with an empty catch block

### ISSUE THREAD

**Issue by jminuscula** [decaffeinate/decaffeinate#583]
```coffee
try
  a = 1 + 1
catch err
  # do nothing
```

http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=try%0A%20%20a%20%3D%201%20%2B%201%0Acatch%20err%0A%20%20%23%20do%20nothing%0A

I get this error:

```
Cannot read property 'outerStart' of null
> 1 | try
> 2 |   a = 1 + 1
> 3 | catch err
  4 |   # do nothing
  5 | 
```

**Comment by alangpierce** [comment]
Thanks for the report, I'll take a look. Seems like it should probably be an easy fix.

**Comment by alangpierce** [comment]
After looking at this a little more, getting this (and other `catch` blocks) exactly correct is a bit more complicated because of a difference in behavior between CS and JS: the catch variable in JS is just scoped to the catch block, but in CS it makes a variable that persists past the end of the catch. For example, this code is valid CS but the equivalent JS code isn't valid:
```coffee
try
  throw new Error('foo')
catch err
  # do nothing
console.log(err)
```

In your case, were you intentionally specifying `catch err` (rather than just `catch`) so that you could use `err` afterward? If so, then I think it would be a slightly bigger change, and I'll file that issue as a separate bug. For this issue, I'll just fix the crash so it generates an empty catch block.

**Comment by jminuscula** [comment]
Thanks for looking into this!

The codebase I was working on was just trying to ignore the exceptions, so an empty catch block is just enough :)
