### ISSUE TITLE
Incorrect compiling coffeescript classes with prototype properties

### ISSUE THREAD

**Issue by artyomtrityak** [decaffeinate/decaffeinate#625]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
define (require) ->
  'use strict'


  class MainLayout extends BaseView
    container: 'body'
```

[Repl link](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=define%20(require)%20-%3E%0A%20%20'use%20strict'%0A%0A%0A%20%20class%20MainLayout%20extends%20BaseView%0A%20%20%20%20container%3A%20'body'%0A)

I get this output:

```js
define(function(require) {
  'use strict';


  class MainLayout extends BaseView {
    static initClass() {
      this.prototype.container = 'body';
    }
  }
  return MainLayout.initClass();
});
```

Here's what I expect it to be instead:

```js
define(function(require) {
  'use strict';


  class MainLayout extends BaseView {
    static initClass() {
      this.prototype.container = 'body';
    }
  }
  MainLayout.initClass();
  return MainLayout;
});
```

So instead of 

```js
return MainLayout.initClass();
```

which will return `undefined` it will be correct to have 

```js
MainLayout.initClass();
return MainLayout;
```

**Comment by alangpierce** [comment]
Thanks for the report. This is similar to #544, although probably different enough that it's fine to have as its own issue. The class transformation stuff happens in the normalize stage in decaffeinate, and it looks like it's not correctly detecting that the class is in an expression context (since it's implicitly returned). Also, expression-style classes with the `initClass` stuff aren't implemented yet anyway. These types of cases in classes are one of the bigger missing pieces in decaffeinate, although hopefully it should be reasonable to implement it before too long.

In the meantime, one workaround is to add an explicit return, like this:

```coffee
define (require) ->
  'use strict'


  class MainLayout extends BaseView
    container: 'body'
  return MainLayout
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=define%20(require)%20-%3E%0A%20%20'use%20strict'%0A%0A%0A%20%20class%20MainLayout%20extends%20BaseView%0A%20%20%20%20container%3A%20'body'%0A%20%20return%20MainLayout%0A)

**Comment by artyomtrityak** [comment]
@alangpierce yeah, i can return but it is a bug :)
