### ISSUE TITLE
Add support for Literate CoffeeScript

### ISSUE THREAD

**Issue by MattMS** [decaffeinate/decaffeinate#714]
I have a feature request.

Would it be difficult to add support for [Literate CoffeeScript](http://coffeescript.org/#literate)?

The main `coffee` command checks for this by file extension (`.coffee.md` and `.litcoffee`) or by argument (`-l`, `--literate`).

All that is required is stripping anything that is not indented as Markdown code (by tab or 4 spaces).

Thanks!

**Comment by alangpierce** [comment]
Sure, that seems reasonable. Since there isn't a Literate JavaScript, what would you want the output to be? I guess all of the code would be unindented and the markdown would just become comments?

**Comment by eventualbuddha** [comment]
>  I guess all of the code would be unindented and the markdown would just become comments?

That's what I'd expect. Probably block comments, or maybe line contents if they are a single line? Not sure.

**Comment by alangpierce** [comment]
Yeah, block comments seem best, although they require a little more care in case the markdown has `*/` in it.

**Comment by MattMS** [comment]
If I was implementing it, I'd just make them all line comments because then I wouldn't have to deal with the `*/` case, but I guess other users would be asking for block comments eventually.

Thanks for the quick response too!
Happy to help out if I can.

**Comment by eventualbuddha** [comment]
I'd probably implement this as a stage before the normalize stage which takes litcoffee and returns normal CoffeeScript code.

**Comment by alangpierce** [comment]
@MattMS thanks, PRs certainly welcome. Some pointers that may be helpful:

CoffeeScript handles this in `invertLiterate` before the lexing step, which is pretty close to what we want.
https://github.com/jashkenas/coffeescript/blob/master/src/helpers.coffee#L73
There's also `isLiterate` in that same file. (Not that you can/should actually use those, just might be good to copy the logic.)

Like @eventualbuddha mentioned, I'd add a new stage to the start that checks `options.filename` to determine whether to do any conversion, and does a CoffeeScript-to-CoffeeScript transform if so. src/index.js has the list of stages. `SemicolonsStage` is probably the easiest to understand if you want an example (although it's a JS -> JS transform). If you're up for the block comment approach, you'd need to generate CoffeeScript-style block comments so that later transforms will turn them into JS block comments.

I guess to make source maps work, you'll want to use magic-string ( https://github.com/Rich-Harris/magic-string ) like all of the other stages do. (Although really I think source maps don't really work in decaffeinate and maybe we shouldn't bother with them.)

To allow input from stdin (which won't have a file extension), I think you'll also want a new `--literate` flag like CoffeeScript has. src/cli.js is where that would go, and I guess it would be a new `options` field like the other flags.

For a test, the `check` function used all throughout the tests has an optional `options` second param that you can specify, both to test the option backing the `--literate` flag and to test file extension detection, so it should be reasonable to just use `check` for all of your tests.

**Comment by MattMS** [comment]
Thanks @alangpierce and @eventualbuddha, I'll have a look through the code and post back here if I make some progress.

**Comment by MattMS** [comment]
Needed to add #720 to start work on this.

**Comment by eventualbuddha** [comment]
Merged, thanks. One other thing: we use Semantic Release to do releases, which means we follow the Angular 2 commit message guidelines. You might want to get a passing familiarity with those, but the gist is this:

* use the appropriate prefix for each commit message:
  * `fix:` prefix for bug fixes
  * `feat:` prefix for features
  * `chore:` prefix for maintenance tasks (e.g. updating dependencies)
  * `refactor:` for refractors that don't change behavior
  * `docs:` for documentation updates
* use imperative style (e.g. `add literate CoffeeScript support`)
* use lowercase on the first line of the commit message without a period
* if backward-incompatible changes are in a commit, add `BREAKING CHANGE:` to the footer of the commit with a description

**Comment by MattMS** [comment]
Thanks for the info, I'll check it out.
I see you also have a PR for updating the contributing docs, which will be useful.

Nice to see you were able to fix the commit message before merging too.
