### ISSUE TITLE
unexpected 'null' index error

### ISSUE THREAD

**Issue by LuckyDino** [decaffeinate/decaffeinate#728]
decaffeinate is crashing on my CoffeeScript input:

```coffee
process((rows) ->
  for line in rows
    if line == 'x'
      foo(x)
)
```

[repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=EsnextStage&code=process((rows)%20-%3E%0A%20%20for%20line%20in%20rows%0A%20%20%20%20if%20line%20%3D%3D%20'x'%0A%20%20%20%20%20%20foo(x)%0A))

I get this error:

```
unexpected 'null' index, perhaps you forgot to check the result of 'indexOfTokenContainingSourceIndex'?
> 1 | process((rows) ->
> 2 |   for line in rows
> 3 |     if line == 'x'
> 4 |       foo(x)
> 5 | )
```

**Comment by alangpierce** [comment]
This doesn't seem to be happening for me, in the repl or when running locally. Not sure exactly what fixed this, but seems like things are working now, possibly due to updating dependencies or something. Anyway, I'll close this, but feel free to reopen if it's still happening for you or if you see it again.
