### ISSUE TITLE
Issue with default arguments

### ISSUE THREAD

**Issue by LuckyDino** [decaffeinate/decaffeinate#729]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
filter = (items, predicate = (-> true)) -> items.filter(predicate)
console.log(filter([1,2,3]))
```

[repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=EsnextStage&code=filter%20%3D%20(items%2C%20predicate%20%3D%20(-%3E%20true))%20-%3E%20items.filter(predicate)%0Aconsole.log(filter(%5B1%2C2%2C3%5D)))

I get this output:

```js
let filter = (items, predicate) => predicate != null ? predicate : (predicate = function() { true; return items.filter(predicate); });
console.log(filter([1,2,3]));
```

Here's what I expect it to be instead:

```js
let filter = function(items, predicate) { 
  if (predicate == null) { predicate = () => true; }
  return items.filter(predicate);
};
console.log(filter([1,2,3]));
```
Incorrect output is returned only when this is written as an one-liner.

**Comment by eventualbuddha** [comment]
@LuckyDino thanks for the report. Looks like running this with `--loose-default-params` makes it work (since it avoids the underlying issue):

```sh
$ echo '
filter = (items, predicate = (-> true)) -> items.filter(predicate)
console.log(filter([1,2,3]))
' | decaffeinate --loose-default-params | node
[ 1, 2, 3 ]
```

@alangpierce The problem seems to be that creating an inline statement that ends in an inline function declaration doesn't work as expected:

```coffee
filter = (items, predicate) -> predicate ?= -> true; items.filter(predicate)
console.log(filter([1,2,3]))
```

The `items.filter(predicate)` statement now becomes part of the predicate. One way to fix this is to wrap the default value in parens (or, in this case, preserve the parens that are already there):

```coffee
filter = (items, predicate) -> predicate ?= (-> true); items.filter(predicate)
console.log(filter([1,2,3]))
```

That becomes this, which works as expected:

```js
let filter = function(items, predicate) { if (predicate == null) { predicate = (() => true); } return items.filter(predicate); };
console.log(filter([1,2,3]));
```
