### ISSUE TITLE
Crash on implicitly-returned `new` expression

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#809]
decaffeinate is crashing on my CoffeeScript input:

```coffee
-> new A().b(c)
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=-%3E%20new%20A().b(c))

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (1:18)
> 1 | (function() { new return A().b(c); });
    |                   ^
```

**Comment by eventualbuddha** [comment]
This is also probably due to the mapper stuff. The old version [explicitly expands to encompass `new`](https://github.com/decaffeinate/decaffeinate-parser/blob/29a052f036199286ff928a1aa40802fc95fb0231/src/parser.js#L351-L354). I try to do that [in `mapNewOp` too](https://github.com/decaffeinate/decaffeinate-parser/blob/29a052f036199286ff928a1aa40802fc95fb0231/src/mappers/mapCall.ts#L134), but it doesn't seem to be working…

**Comment by alangpierce** [comment]
Ah, yeah, that's annoying...

This is what I have so far: https://github.com/alangpierce/decaffeinate-parser/commit/20962fe79f99bfb5e2d5bc6a53aad704fe4ecd4b , but there are some test failures. Seems like the right fix may be at the CoffeeScript parser level so the range includes the `new` token.

**Comment by eventualbuddha** [comment]
> Seems like the right fix may be at the CoffeeScript parser level so the range includes the `new` token.

I'd be fine with that. Actually, everywhere we do location changes would be a good candidate for such a patch. Want to handle this one?

**Comment by alangpierce** [comment]
👍 sure, I'll take a look. Hopefully it won't be so different from the previous location fixes.
