### ISSUE TITLE
Automatically convert object exports to named exports

### ISSUE THREAD

**Issue by CliffFox** [decaffeinate/decaffeinate#904]
I'm not sure if my issue is a bug, a feature request, or user error.

The core of the issue is that es6 does not let you destructure exported objects in the same way that coffeescript does.

Here's a minimal example of the issue I'm dealing with:
Suppose my project is two files, `index.coffee` and `constants.coffee`, with the following contents:
index.coffee:
```
{bar} = require './constants'
console.log bar
```
constants.coffee:
```
module.exports =
  foo: 1
  bar: 3.14
```
If you execute `index.coffee`, it prints 3.14 to the console, as you might expect.

Now, if you run bulk-decaffeinate on this project, it transforms it to:
index.js:
```
import { bar } from './constants';
console.log(bar);
```
constants.js
```
export default {
  foo: 1,
  bar: 3.14
};
```
If you execute this (with babel's es-2015 preset), it prints undefined, because the `import {bar} from './constants'` does not work. See [this blog post](https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0#.inj8rq947) for a thorough discussion of this change. There are a few options for making these exports work like the coffee exports did. One would be to define the names separately and export them separately:
```
const foo = 1;
const bar = 3.14;
export {foo, bar};
```

I'm working on converting a ~150-file project, and this export/import snafu has created a good amount of manual work. Is this a bug? Or should I be taking a different approach to converting these exports?

PS: Thank you very much for working on this terrific project! It has already had a big impact on our team, and I am very much looking forward to living in a coffee-free world.

**Comment by alangpierce** [comment]
Hey @CliffFox, thanks for the kind words.

I've run into this as well and currently you have two options:

* bulk-decaffeinate has an optional "fix imports" step that fixes all imports to match the export on the other side. Since it's a cross-file operation, it can't be done as part of the core decaffeinate tool, so it's a follow-up step in bulk-decaffeinate. See `fixImportsConfig` in the [bulk-decaffeinate README](https://github.com/decaffeinate/bulk-decaffeinate#configuration).
* You can set the `--keep-commonjs` flag for decaffeinate, which disables the transformation to import statements. I ended up needing to do this for my codebase (at least for now) since otherwise it causes problems with test mocking/patching, and all of the example projects on the README have this set.

Another possibility is to make decaffeinate more defensive and just always generate default imports and exports instead of named imports/exports. Although I think there may be some tricky details there, e.g. if a existing CoffeeScript file uses an existing JavaScript file that has named exports. Certainly, it would be great to have some way to use the JS import/export syntax if there's a way to make sure it's completely correct.

I'll keep this issue open until there's at least better documentation about this.

**Comment by alangpierce** [comment]
And agreed that ideally decaffeinate would use named exports in your example, but it's not always possible to generate code with named exports. CommonJS exports can have a dynamic set of keys that's computed at runtime and named exports can't. The safest approach, I think, is to just export an object, and then at import time, do an import followed by a separate destructure assignment.

**Comment by CliffFox** [comment]
Thanks for the insights @alangpierce. I hear what you're saying about object export followed by destructure being the safest option. `fixImportsConfig` seems to be working well for me. Thanks!
