### ISSUE TITLE
Support for custom patchers

### ISSUE THREAD

**Issue by bennyn** [decaffeinate/decaffeinate#981]
At [Wire](https://wire.com/) we use the [decaffeinate REPL](http://decaffeinate-project.org/repl/) to convert [our CoffeeScript code base](https://github.com/wireapp/wire-webapp) into JavaScript.

In our CoffeeScript code we have a lot of Coffeedoc declarations because we built our documentation using [codo](https://github.com/coffeedoc/codo). With plain JavaScript code we now need to convert our Coffeedoc into valid [JSDoc 3](http://usejsdoc.org/). Doing this, we realized that decaffeinate doesn't convert Coffeedoc to proper JSDoc. 

Let me show you an example.

**CoffeeScript input**

```coffeescript
###
Create a new conversation.

@param name [String] Name of conversation
@param user_ids [Array<String>] IDs of users
@return [z.entity.Conversation] Returns a new conversation entity.
###
```

**Decaffinated output**

```javascript
/*
Create a new conversation.

@param name [String] Name of conversation
@param user_ids [Array<String>] IDs of users
@return [z.entity.Conversation] Returns a new conversation entity.
*/
```

**Expected output (JSDoc)**

```javascript
/**
 * Create a new conversation.
 *
 * @param {String} name - Name of conversation
 * @param {Array<String>} user_ids - IDs of users
 * @returns {z.entity.Conversation} Returns a new conversation entity.
 */
```

I checked your code and found the [patchComments method](https://github.com/decaffeinate/decaffeinate/blob/v2.52.12/src/stages/main/patchers/ProgramPatcher.js#L47) which replaces CoffeeScript style comments with JavaScript style comments. Does decaffinate support to write a custom patcher, so that you can define your own replacement style?

**Comment by alangpierce** [comment]
Hi, the short answer is that right now there's no support for custom patchers/plugins, and I'd generally prefer to avoid it if possible, since the CoffeeScript -> JavaScript stage is fairly fragile. I think in most cases you can solve those types of problems by either doing a CoffeeScript -> CoffeeScript transform ahead of time or a JavaScript -> JavaScript transform after the fact. (JS generally has better tooling, like [jscodeshift](https://github.com/facebook/jscodeshift), so I'd suggest the JS approach if possible. Also, [bulk-decaffeinate](https://github.com/decaffeinate/bulk-decaffeinate) lets you specify jscodeshift scripts to automatically run after decaffeinate finishes.)

Also, generally it feels a little weird to change *every* multiline/block comment into a jsdoc comment, since at least from my experience you usually would have some that document functions/etc and some that are just multiline comments in the middle of a function.

My understanding is the usual way to write JSDoc in CoffeeScript is to write it like this:

```coffee
###*
# Create a new conversation.
#
# @param name [String] Name of conversation
# @param user_ids [Array<String>] IDs of users
# @return [z.entity.Conversation] Returns a new conversation entity.
###
```

Both decaffeinate and the CoffeeScript compiler convert it to this:

```js
/**
 * Create a new conversation.
 *
 * @param name [String] Name of conversation
 * @param user_ids [Array<String>] IDs of users
 * @return [z.entity.Conversation] Returns a new conversation entity.
 */
```

Maybe you could change your CoffeeScript code to use that style, if it's recognized by codo? Happy to help brainstorm other approaches if that doesn't work or is a pain.

**Comment by bennyn** [comment]
Thanks @alangpierce for your quick and detailed answer!

The subject is somewhat more complicated. Converting CoffeeDoc to proper JSDoc needs more than just additional asterisks.

Here are a few of the things to consider:
- CoffeeDoc uses square brackets to define parameter types, JSDoc uses curved brackets (`[Object]` vs. `{Object}`)
- CoffeeDoc uses `<>` to define arrays, JSDoc uses Closure Compiler's syntax for defining arrays (`Array<MyClass>` vs. `Array.<MyClass>`)
- CoffeeDoc puts the parameter name before the parameter type, JSDoc puts the parameter type first (`name [String]` vs. `{String} name`)
- CoffeeDoc prefers `@return` to set the return value of a function, JSDoc prefers `@returns`  (`@return` vs. `@returns`)
- There can be dashes in JSDoc to separate the parameter type from the parameter name, CoffeeDoc doesn't support that

Ofcourse we could touch all our CoffeeDoc comments and turn them into something that's easy to convert into JSDoc but I don't want to go that way because it means that we will have CoffeeScript code with invalid CoffeeDoc comments. But we want to convert proper CoffeeScript code with proper CoffeeDoc into proper JavaScript code with proper JSDoc. It is a matter of integrity.

Taking all this into consideration, the best workaround for us at the moment would be to fork "decaffeinate", so that we can patch the `patchComments` function according to our needs. But I thought it might be a good idea to reach out to you first and ask for support of custom patchers / custom writers because this would make decaffinate more useful and it would solve our issue in a generic way which is always a big plus.

A lot of parsers offer the option to define your own writers. A good example is the "marked" Markdown parser: https://github.com/chjj/marked#overriding-renderer-methods - I really see a big benefit for decaffinate offering something similar. 😃

**Comment by alangpierce** [comment]
Make sense, I didn't notice the syntax differences. Just to brainstorm all the options I can think of:

* You could fork decaffeinate, as you mentioned. You are of course welcome to do that. 😃 
* You could add an opt-in option to decaffeinate to automatically convert coffeedoc to jsdoc. Assuming the code isn't too intrusive/fragile, it seems reasonable to accept as a PR. I don't think I've seen coffeedoc used in any projects I've worked with, but certainly it seems like a reasonable thing that other projects might want to do, and it's certainly in line with decaffeinate's goal of making it easier for anyone to do a CoffeeScript -> JavaScript codebase conversion.
* You could write a wrapper tool that does a CoffeeScript -> CoffeeScript doc conversion, then calls decaffeinate. You wouldn't need to commit the intermediate file, so I don't really think it would be an integrity issue.
* You could write a wrapper tool that calls decaffeinate, then does a JavaScript -> JavaScript doc conversion. I'd do this using [bulk-decaffeinate](https://github.com/decaffeinate/bulk-decaffeinate) specifying a custom jscodeshift script. jscodeshift is particularly nice because it lets you use the ASTExplorer website to develop the script. I threw together an incomplete example for what that type of thing would look like: https://astexplorer.net/#/gist/b2dafffb70bfd687f2dddb884bffd258/ab210eb46c9b69a67477f0abfaf96deba474b98c . This is the option that I would do, I think.
* decaffeinate could add an extensibility point that allows you to specify a custom comment transformer. This would probably fit your use case, although it seems specific enough that it likely wouldn't get any other usage.
* decaffeinate could add an extensibility point that allows you to specify a custom patcher for any node type. Given that comments are not patched as normal nodes at the moment, it may also be necessary to refactor decaffeinate first to fit your use case. Also, given that decaffeinate patches code in-place, it seems like it would be really difficult to write custom patchers that are reliable. The magic-string library requires you to be pretty careful about the order and position of code patching, so there are lots of subtle interactions between node types within decaffeinate at the moment.

One thing to note in the decaffeinate-specific versions of these is that you sometimes won't be able to just replace the old comment text with the new comment text, since it might have had some previous changes made to it that would be lost, like indentation being added. Ideally you'd express the transform as a set of specific magic-string transforms (`insert`, `overwrite`, `remove`). Although I think you could also call `this.slice(commentStart, commentEnd)` to get the latest version of the code including any indentation changes. But really, like I mentioned, IMO it seems safest to try to accomplish this as a transform outside of the core CoffeeScript -> JavaScript stage within decaffeinate.

**Comment by alangpierce** [comment]
Closing for now since I think there are a few good alternatives to a plugin system. But happy to continue the discussion if you want.

**Comment by bennyn** [comment]
Hi @alangpierce, thanks for your detailed answer. This is by far the best answer I received on a GitHub issue! 😃 

I will go with your **suggestion no. 3**: Wrapper tool which does CoffeeScript → Intermediate CoffeeScript (with JSDoc-friendly conversion) → Decaffinate

In the meantime I hacked together a small website which does pure CoffeeDoc to JSDoc 3 conversion. It's just a quick and dirty hack but "done is better than perfect": https://github.com/bennyn/coffeedoc2jsdoc 😄
